alicevision/AliceVision

- src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp
- src/openMVG/sfm/pipelines/sequential/sequential_SfM.hpp
- src/software/SfM/main_IncrementalSfM.cpp
It exposes a parameter to set a minimum length for the tracks to be used in the SfM reconstruction.
> [sfm] Add min input track length parameter

- src/CMakeLists.txt
- src/openMVG/sfm/pipelines/localization/SfM_Localizer.cpp
- src/openMVG/sfm/sfm_data_BA_ceres.hpp
- src/openMVG_Samples/robust_essential_spherical/robust_essential_spherical.cpp
* Add `OpenMVG_USE_POPART_LOG` in cmake to build with the logger
* reverted changes of c9da3ed so that the logs are enabled by default
> Re-enable logs and cmake variable to set it

- src/openMVG/features/svgVisualization.cpp
- src/openMVG/features/svgVisualization.hpp
- src/openMVG/localization/CCTagLocalizer.cpp
- src/openMVG/localization/VoctreeLocalizer.cpp
- src/software/SfM/main_ComputeCCTagStructureFromKnownPoses.cpp
Since 634c3eca9f079ee21920f87e720c3c7f75cb0110 svgVisualization has been moved from module `localization` to module `features` but its namespace was still `openMVG::localization`.
> [features][localization] update the namespace of svgVisualization

- src/openMVG/features/cctag/CCTAG_describer.cpp
- src/openMVG/features/cctag/CCTAG_describer.hpp
- src/openMVG/features/cctag/SIFT_CCTAG_describer.hpp
- src/openMVG/localization/VoctreeLocalizer.cpp
- src/openMVG/localization/VoctreeLocalizer.hpp
- src/software/RigCalibration/main_rigCalibration.cpp
This option enables us to use cctag without gpu. Default is on as before.
CUDA is turned off in rig calibration, as CUDA CCTAG does not yet
support changing resolutions (two cameras are at different resolutions).
> Infrastructure for on-demand disabling of CUDA in SIFT_CCTAG_describer.

- src/openMVG/rig/Rig.cpp
- src/openMVG/rig/Rig.hpp
- src/software/RigCalibration/main_rigCalibration.cpp
connected to poparteu/openMVG#145
Fixes:
* ~~Add `OpenMVG_USE_POPART_LOG` in cmake to build with the logger~~  this is now in poparteu/openMVG#148 
* Fixes uncatched errors in main_rigCalibration
* Fixes a bug for `vMainPoses` which was accessed with improper indices
* Add some more asserts/checks
> Fix rig calibration

- src/software/Localization/voctreeQueryUtility.cpp
Compilation fails when opencv are disabled.
OpenCV is not required for this binary
see https://github.com/poparteu/openMVG/pull/151#discussion_r67608065
> [localization] removed useless includes

- src/openMVG/features/cctag/CCTAG_describer.cpp
- src/openMVG/features/cctag/CCTAG_describer.hpp
- src/openMVG/features/cctag/SIFT_CCTAG_describer.cpp
- src/openMVG/features/cctag/SIFT_CCTAG_describer.hpp
Serialization was producing an empty file for image describer and thus when using it in computeFeatures the parameters alwqys had the default value.
> Fix SIFT_CCTAG_describer serialization

- src/software/SfM/main_SfMInit_ImageListing.cpp
- src/third_party/easyexif/exif.cpp
some checks are removed because some valid JPEG files are not recognized.
> [exif] avoid unrecognized JPEG files

- src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
Nice to have when using WC/SDI for reconstruction.
Exif data can be added like this:
exiftool -Make='PtGrey' -Model='Grasshopper3 1920x1440' -FocalLength='3.5 mm' *.jpg
> Add Grasshopper and RED variants to camera db.

- src/software/Localization/main_cameraLocalizer.cpp
Allow cameraLocalizer to save all the export files (abc, localization results and tiny scene sfmdata) in any directory other than the current folder
> [software] fix export file supporting different path than current folder

- src/software/SfM/main_openMVG2MVE2.cpp
- Fix remapping view ID to index for camera and for 3D points
visibility.
- Don't export unreconstructed views: as we are doing a remapping from
viewId to viewIndex, it doesnt make sense to keep unreconstructed views.
Note: MVE supports unreconstructed views but not random IDs (as we can
do in openMVG with UID). MVE checks that "view_id < views.size()":
https://github.com/simonfuhrmann/mve/blob/8464613b6608a4fc7faee467397aba59fd0214f4/apps/dmrecon/dmrecon.cc#L289
> MVE export fix to enable UID support

- src/openMVG/cameras/Camera_Intrinsics.hpp
- src/openMVG/localization/optimization.cpp
- src/openMVG/sfm/pipelines/global/sfm_global_engine_relative_motions.cpp
- src/openMVG/sfm/pipelines/localization/SfM_Localizer.cpp
- src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp
- src/openMVG/sfm/pipelines/sequential/sequential_SfM_test.cpp
- src/openMVG/sfm/sfm_data_BA.hpp
- src/openMVG/sfm/sfm_data_BA_ceres.cpp
- src/openMVG/sfm/sfm_data_filters.hpp
- src/software/SfM/main_SfMInit_ImageListing.cpp
* add boundaries on optical center
* add boundaries on focal length if an initial guess was provided
* add options to refine intrinsics subparts: BA_REFINE_INTRINSICS_FOCAL,
BA_REFINE_INTRINSICS_OPTICALCENTER_ALWAYS,
BA_REFINE_INTRINSICS_DISTORTION
* add an option to refine the optical center only if we have enough
constraints / enough input images with the same intrinsics:
BA_REFINE_INTRINSICS_OPTICALCENTER_IF_ENOUGH_DATA
connected to poparteu/openMVG#31
> [sfm] BA: add options to refine intrinsics subparts and add boundaries

- src/openMVG/sfm/AlembicExporter.cpp
- src/openMVG/sfm/AlembicExporter.hpp
- src/openMVG/sfm/AlembicImporter.cpp
- src/openMVG/sfm/AlembicImporter.hpp
- src/openMVG/sfm/sfm_data_io_gt.cpp
- src/openMVG/sfm/sfm_data_io_gt.hpp
- src/software/Localization/main_cameraLocalizer.cpp
- src/software/SfM/CMakeLists.txt
- src/software/SfM/main_ConvertAnimatedCamera.cpp
This PR fixes the sampling system during Alembic import. Instead of using time samples to retrieve the poses of the cameras, it just uses indices to access to each sample. This avoid issues given by (possible) different frame rates of the animations.
There is also a debug program that converts a ground truth folder-format (containing subfolders `gt` and `images`) in an Alembic file.
It also fixes the bug poparteu/openMVG#166 (localization application crashed due to Alembic if first frame is not localized). (connect to poparteu/openMVG#166)
> [WIP] Fix Alembic importer for animated cameras

- src/openMVG/sfm/pipelines/localization/SfM_Localizer.cpp
kernel.normalizer2 is the inverse of K, so we need to multiply by the inverse of the focal.
This implementation really sucks, as mentioned in the comment... need refactoring asap!!
> [sfm] bugfix localize loransac, wrong normalization for threshold

- src/openMVG/calibration/CMakeLists.txt
- src/openMVG/calibration/calibration.cpp
- src/openMVG/calibration/calibration.hpp
- src/openMVG/calibration/patternDetect.cpp
- src/openMVG/dataio/ImageFeed.cpp
- src/openMVG/features/cctag/CCTAG_describer.cpp
- src/openMVG/localization/CCTagLocalizer.cpp
- src/openMVG/localization/CCTagLocalizer.hpp
- src/openMVG/localization/CMakeLists.txt
- src/openMVG/localization/VoctreeLocalizer.cpp
- src/openMVG/localization/rigResection.cpp
- src/openMVG/system/timer.cpp
- src/openMVG/system/timer.hpp
- src/software/RigCalibration/CMakeLists.txt
- src/software/RigCalibration/main_cameraCalibration.cpp
Some improvements for the cctag localizer
* updated the cctag describer according to the latest API 
* better debugging organization, the matchings for each query image are saved in a separate folder
* missing set preset for cctag
* implemented a new method for localization that collects first all the association and the it estimates the pose
Spur of the moments bugfixes
* fixed a major bug for naive method in both cctag and voctree 77f09e2
* fixed another major bug for opengv method concerning undistortion (connected to poparteu/openMVG#225)
> [WIP] some fixes for cctags

- src/openMVG/sfm/AlembicExporter.cpp
- src/openMVG/sfm/AlembicExporter.hpp
- src/openMVG/sfm/AlembicImporter.cpp
- src/openMVG/sfm/AlembicImporter.hpp
- src/software/Localization/main_rigLocalizer.cpp
Hidden implementation of Alembic{Im,Ex}porter avoids having to include alembic headers in openMVG headers.
Now, in theory, we don't need to find Alembic when using openMVG as external library
connected to poparteu/openMVG#221
> Pimpl'ed alembic

- src/software/RigCalibration/CMakeLists.txt
openMVG_main_cameraCalibration must include CCTAG when linking if they are available
> [cmake] missing linking of CCTAG

- src/software/SfM/main_convert2UID.cpp
This main applies the new rule for naming of .desc and .feat files
From <pictureName>.desc to <uid>.desc, if the uid option is on,
or <index>.desc, if the uid option is off.
It goes the same way for the .feat files.
> [camera_uid] main for backward compatibility

- src/openMVG/matching_image_collection/Cascade_Hashing_Matcher_Regions_AllInMemory.cpp
- src/openMVG/matching_image_collection/GeometricFilter.hpp
- src/openMVG/types.hpp
Clang 3.9 is more strict with const/no-const qualifiers.
> Clang 3.9 fix

- src/openMVG/robust_estimation/robust_estimator_LORansac_test.cpp
* loosen the threshold
* do not run test with noise as results may vary according to the generated data
> Fix lo ransac test failures

- src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp
Even though .count() (more efficient version here) does not modify the
data-structure, other threads running in parallel might be doing so.
When traversal encounters a data structure which is in process of being
modified, .count() called std::distance on pair of iterators returned by
equal_range where first > second.  Thus, infinite loop in distance.
> Bugfix for race condition leading to infinite loop.

- .travis.yml
When executing the tests, the ones using openmp take a lot of time because travis tries to use all the threads on the physical machine but only few of them (eg 4) are available on the VM for the job.
See here https://docs.travis-ci.com/user/languages/cpp/#OpenMP-projects
Fixing num threads to a reasonable value, dramatically improves the test performances, eg
without the fix https://travis-ci.org/alicevision/openMVG/builds/231209785#L4100
Total Test time (real) = 657.67 sec
with the fix https://travis-ci.org/alicevision/openMVG/builds/232087029#L4107
Total Test time (real) =  15.58 sec
> [ci] set num threads for omp when testing

- src/openMVG/localization/VoctreeLocalizer.cpp
During the compilation, this error occured:
`[ 96%] Building CXX object openMVG/localization/CMakeFiles/openMVG_localization.dir/VoctreeLocalizer.cpp.o
In file included from /usr/include/eigen3/Eigen/Core:297:0,
from /home/cdebize/Softwares/AliceVision/openMVG/src/openMVG/types.hpp:12,
from /home/cdebize/Softwares/AliceVision/openMVG/src/openMVG/localization/reconstructed_regions.hpp:11,
from /home/cdebize/Softwares/AliceVision/openMVG/src/openMVG/localization/VoctreeLocalizer.hpp:10,
from /home/cdebize/Softwares/AliceVision/openMVG/src/openMVG/localization/VoctreeLocalizer.cpp:1:
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h: In instantiation of ‘Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::coeff(Eigen::Index) const [with Derived = …
> bugfix: compilation failed because of a bad 'auto' management.

- src/CMakeLists.txt
- src/aliceVision/image/CMakeLists.txt
OpenEXR must be treated as a direct dependency and not just rely on OIIO
(because of this https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/image/io.cpp#L13)
> [cmake] OpenEXR is a direct dependency

- src/software/pipeline/main_featureExtraction.cpp
Fix build when neither POPSIFT nor CCTAG (based on CUDA) is built.
> FeatureExtraction: don't call CUDA code if no GPU feature  is available

- src/aliceVision/mesh/Mesh.cpp
- src/aliceVision/mesh/MeshAnalyze.cpp
- src/aliceVision/mesh/MeshClean.cpp
- src/aliceVision/mesh/MeshEnergyOpt.cpp
- src/aliceVision/mesh/MeshEnergyOpt.hpp
- src/aliceVision/mesh/meshPostProcessing.cpp
- src/software/pipeline/main_meshFiltering.cpp
> Fix mesh filtering

- src/aliceVision/feature/CMakeLists.txt
- src/aliceVision/feature/ImageDescriber.cpp
- src/aliceVision/feature/ImageDescriber.hpp
- src/aliceVision/image/CMakeLists.txt
- src/aliceVision/image/io.cpp
- src/aliceVision/imageIO/CMakeLists.txt
- src/aliceVision/imageIO/image.cpp
- src/aliceVision/matching/io.cpp
- src/aliceVision/sfm/sfmDataIO.cpp
Use a temporary filename when saving:
- images files
- matches files
- feature (`.feat` & `.desc`) files
- sfmData files
> Use a temporary filename when saving a file

- src/aliceVision/imageIO/image.cpp
- src/aliceVision/imageIO/image.hpp
- src/aliceVision/mesh/Texturing.cpp
- src/aliceVision/mesh/Texturing.hpp
- src/software/pipeline/main_texturing.cpp
Add additional options to texturing
> Texturing: fill holes and unwrap methods

- src/aliceVision/mesh/Mesh.cpp
- src/aliceVision/mesh/Mesh.hpp
- src/aliceVision/mesh/Texturing.cpp
- src/aliceVision/mesh/Texturing.hpp
- src/software/pipeline/main_meshFiltering.cpp
- src/software/pipeline/main_texturing.cpp
Fixes a few issues in the texturing step.
> Texturing: fix 2D triangle bounding box computation and mesh loading

- src/CMakeLists.txt
- src/aliceVision/calibration/CMakeLists.txt
- src/aliceVision/feature/CMakeLists.txt
- src/samples/featuresRepeatability/CMakeLists.txt
- src/samples/imageDescriberMatches/CMakeLists.txt
- src/samples/kvldFilter/CMakeLists.txt
- src/samples/robustFundamental/CMakeLists.txt
- src/samples/sensorWidthDatabase/CMakeLists.txt
- src/samples/undistoBrown/CMakeLists.txt
- src/software/convert/CMakeLists.txt
- src/software/export/CMakeLists.txt
- src/software/pipeline/CMakeLists.txt
- src/software/utils/CMakeLists.txt
Unify case of 'Boost_LIBRARIES' variable in CMake files.
> [cmake] use 'Boost_LIBRARIES' instead of 'BOOST_LIBRARIES'

- src/aliceVision/mesh/Texturing.cpp
Current camera index was not properly incremented in all cases, leading to incoherent colors in output textures.
> Texturing: fix potentially invalid camera index while generating textures

- src/aliceVision/depthMap/CMakeLists.txt
- src/aliceVision/fuseCut/CMakeLists.txt
- src/dependencies/CMakeLists.txt
> [cmake] add missing cublas link for depthMap

- src/aliceVision/camera/Pinhole.hpp
- src/aliceVision/sfm/pipeline/sequential/sequentialSfM_test.cpp
- src/aliceVision/sfm/sfmDataIO_json.cpp
- src/aliceVision/sfm/viewIO.cpp
- src/software/pipeline/main_cameraInit.cpp
When we set an initial focal length it adds constraints in the BA. So we should set it only when the focal length information is reliable.
> Initial focal length

- src/aliceVision/depthMap/cuda/PlaneSweepingCuda.cpp
- src/aliceVision/depthMap/cuda/PlaneSweepingCuda.hpp
- src/aliceVision/depthMap/cuda/planeSweeping/device_code_refine.cu
- src/aliceVision/depthMap/cuda/planeSweeping/plane_sweeping_cuda.cu
The CUDA kernel ComputeSobelTarIm is buggy (reads uchar from a texture but treats it like
a normalized float). Following the dependency upwards exposed a dead top-level function. The
obviously dead code is now in C comments or (if C comments inside) in #if-0 statements.
> [cleanup] Remove unused code with bug inside

- CMakeLists.txt
* wrong downloaded version
* do not try to extract downloaded file (`DOWNLOAD_NO_EXTRACT 1`)
* file is stored in `${BUILD_DIR}/src/` instead of `<SOURCE>`
> [cmake] 3 bug fixes for cuda installation

- src/CMakeLists.txt
- src/aliceVision/sensorDB/CMakeLists.txt
These changes are necessary to successfully compile AliceVision with external Boost 1.67.0.
> Boost build fixes (Linux)

- src/aliceVision/matchingImageCollection/GeometricFilter.hpp
Clang 3.9 complains about the constness violation of `std::make_pair` for 
```c+++
out_geometricMatches.insert(std::make_pair(currentPair, std::move(inliers)));
```
as `currentPair` is declared as const.
Using emplace is better than insert and it fixes the problem.
Here the log errro
```
In file included from 
AliceVision/src/software/pipeline/main_featureMatching.cpp:19:
AliceVision/src/aliceVision/matchingImageCollection/GeometricFilter.hpp:80:54: error: binding value of type 'const pair<...>' to reference to type 'pair<...>' drops
'const' qualifier
out_geometricMatches.insert(std::make_pair(currentPair, std::move(inliers)));
^~~~~~~~~~~
AliceVision/src/software/pipeline/main_featureMatching.cpp:398:32: note: in instantiation of function template specialization …
```
> [matchingImageCollection] fix clang constness issue

- src/aliceVision/sfm/sfmDataIO_json.cpp
When loading data from json (`loadJSON()`), the view has no height and width on the json file so it is set to 0. 
This leads `updateIncompleteView()` to recompute the UID and all the other information (even if all the data is correct and complete). 
This is a bit of waste of time and, above all, it is not guaranteed that across platforms or compilers the computed UID is the same, thus leading to an exception/error in `updateIncompleteView()` because the new UID is different from the previously UID assigned to the pose. 
see here
https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/sfm/viewIO.cpp#L62
The proposed solution is to update view's width and height before calling `updateIncompleteView()` by getting the values from the relevant intrinsics (if any).
This also …
> [sfm] update view's width and height 

- INSTALL.md
- src/aliceVision/linearProgramming/MOSEKSolver.cpp
- src/aliceVision/linearProgramming/lInfinityCV/triplet_tijsAndXis_kernel.hpp
Logging functions were missing declarations and one usage was missing a closing paren (with minor spelling fix).
Still missing a fix for `error: control reaches end of non-void function [-Werror=return-type]` but I will leave that for real C(++) devs.
> Fix: missing declaration of logging functions in MOSEK

- INSTALL.md
- appveyor.yml
- src/CMakeLists.txt
Fixes Ceres SuiteSparse component requirement which was actually OFF by default.
> [build] Fix Ceres with SuiteSparse requirements + update doc

- appveyor.yml
This PR aims to use AliceVision VCPKG fork on appVeyor to avoid build failures due to uncontrolled updates of preinstalled VCPKG version.
> [ci][appVeyor] use aliceVision vcpkg fork

- src/cmake/FindMAGMA.cmake
Fix FindMAGMA.cmake not working with MAGMA_ROOT defined in cmake invocation `-DMAGMA_ROOT={@}`.
> Fix conditional statement in FindMAGMA.cmake

- src/software/utils/main_computeUncertainty.cpp
`src/software/utils/main_computeUncertainty.cpp` is missing VERSION tags witch prevents cmake from getting through the configuration pass.
> Fix missing VERSION in src/software/utils/main_computeUncertainty.cpp

- src/software/utils/main_computeUncertainty.cpp
After #455 `main_computeUncertainty` needs an update.
> Fix sfmData missing in main_computeUncertainty.cpp

- src/aliceVision/mesh/CMakeLists.txt
- src/aliceVision/mesh/Mesh.cpp
- src/aliceVision/mesh/Mesh.hpp
- src/aliceVision/mesh/Texturing.cpp
- src/aliceVision/mesh/Texturing.hpp
- src/aliceVision/mesh/UVAtlas.cpp
- src/aliceVision/mesh/geoMesh.hpp
- src/aliceVision/mesh/meshVisibility.cpp
- src/aliceVision/mesh/meshVisibility.hpp
- src/aliceVision/mvsData/Pixel.hpp
- src/aliceVision/mvsData/geometry.cpp
- src/aliceVision/mvsUtils/ImagesCache.cpp
- src/aliceVision/mvsUtils/MultiViewParams.cpp
- src/aliceVision/mvsUtils/MultiViewParams.hpp
- src/aliceVision/mvsUtils/common.cpp
- src/aliceVision/mvsUtils/common.hpp
- src/software/pipeline/main_texturing.cpp
Major texturing quality improvement by scoring the image contributions and selecting the best ones.
Improve re-texturing of user mesh after retopology by improving reconstruction visibility remapping to the user mesh.
Instead of pulling visibilities from vertices to vertices, we push the vertices visibilities from the original mesh to the triangles of the user mesh (low poly).
For each triangle, score each image contribution based on projected area to select the best ones. Option to limit the number of image contribution to the N best ones. Option to select a score ratio regarding the best one.
Use geogram Mesh_AABB (Axis Aligned Bounding Box) trees to search for the closest triangle.
> Texturing visibility remapping and texture fusion

- src/aliceVision/sfm/CMakeLists.txt
- src/aliceVision/sfmDataIO/CMakeLists.txt
Fix a CMake mistake with `Boost_REGEX_LIBRARY` in #455 
Fix #471
> [sfmDataIO] fix missing `Boost_REGEX` build error

- src/aliceVision/sensorDB/cameraSensors.db
add the Fujifilm FinePix XP90 to cameraSensors.db
To fix error:
```
[error] Sensor width doesn't exist in the database for image(s) :
[error] image: 'DSCF0690.JPG'
- camera brand: FUJIFILM
- camera model: FinePix XP90 XP91 XP95
[error] Please add camera model(s) and sensor width(s) in the database.
```
> Update cameraSensors.db with Fujifilm FinePix XP90

- INSTALL.md
I believe it's more grammatically correct to use "build" with the "ing" ending in the sentence below. Vcpkg is also a package manager, which let's you download packages in addition to installing them. The previous sentence did not really reflect this fact.  
> Vcpkg is a tool that helps with the acquiring, building, and management of C/C++ libraries.
> Grammar fix

- src/aliceVision/sensorDB/cameraSensors.db
Added Microsoft Lumia 950 Dual SIM to cameraSensors.db to fix the following error:
>[error] Sensor width doesn't exist in the database for image(s) :
>[error] image: 'WP_20180904_21_11_38_Rich.jpg'
>        - camera brand: Microsoft
>        - camera model: Lumia 950 Dual SIM
>
>[error] Please add camera model(s) and sensor width(s) in the database.
> Added Microsoft Lumia 950 Dual SIM to cameraSensors.db

- src/aliceVision/sensorDB/cameraSensors.db
Adds the 5D Mark IV to the sensor database.
> Add Canon 5D Mark IV to sensor database

- src/aliceVision/depthMap/SemiGlobalMatchingVolume.cpp
- src/aliceVision/matching/io.cpp
- src/aliceVision/mesh/Mesh.cpp
Small bugfixes in the pipeline.
Fixes #514 
Fixes https://github.com/alicevision/meshroom/issues/236
> Fix misc bugs

- src/cmake/CXX11.cmake
fix CXX11 test: on osx CMAKE_CXX_COMPILER_ID is "AppleClang"
> [cmake] Minor fix for CXX11 test on OSX

- src/aliceVision/system/gpu.hpp
avoid error: use of 'auto' in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
Fix #526
> [system] build fix: auto in lambda declaration is c++14

- src/aliceVision/sfmDataIO/jsonIO.cpp
- src/aliceVision/sfmDataIO/jsonIO.hpp
This commit does not break compatibility with previous scenes.
Previous json files with bool write as string are still readable.
> [sfmDataIO]  `jsonIO` Fix: write bool as `0` or `1`

- src/aliceVision/sensorDB/cameraSensors.db
> [sensorDB] Add `OLYMPUS E-M1 Mark II` to the sensor database

- src/software/utils/main_computeUncertainty.cpp
Update compute computeUncertainty after [sfm] drops BA_Refine enum.
> `BundleAdjustment` formatting update propagate.

- src/aliceVision/feature/cctag/ImageDescriber_CCTAG.cpp
> [feature] Bug fix: `WITH_CUDA` is now `CCTAG_WITH_CUDA`

- src/aliceVision/CMakeLists.txt
- src/aliceVision/image/Image.hpp
- src/aliceVision/lightingEstimation/CMakeLists.txt
- src/aliceVision/lightingEstimation/augmentedNormals.cpp
- src/aliceVision/lightingEstimation/augmentedNormals.hpp
- src/aliceVision/lightingEstimation/lightingEstimation.cpp
- src/aliceVision/lightingEstimation/lightingEstimation.hpp
- src/aliceVision/lightingEstimation/lightingEstimation_test.cpp
Lighting estimation module:
- define augmented normals and augmented lighting vector for spherical harmonic model;
- lighting evaluation from albedo, picture and normals (linear least-square problem).
> Dev lighting estimation

- src/CMakeLists.txt
- src/aliceVision/sfm/utils/alignment.cpp
- src/aliceVision/sfm/utils/alignment.hpp
- src/aliceVision/sfmData/View.hpp
- src/software/utils/main_sfmTransform.cpp
Enable the specification of one view as the origin of the coordinate system.
Alignement.cpp contains a new function "computeNewCoordinateSystemFromSingleCamera". The name of the view to be used as the origin is a parameter of this function.
The meshroom python interface has been updated to support this feature.
> Allows SfMTransform to use a view as the origin for the coordinate system

- src/aliceVision/sfm/BundleAdjustmentCeres.cpp
Fix unhandled out_of_range exception while iterating over intrinsics.
> [sfm] BundleAdjustment: skip unused intrinsics in addIntrinsicsToProblem

- src/aliceVision/sensorDB/Datasheet.cpp
The "Make" value is inconsistent from one image to another from the same manufacturer.
This weaker test will enable to recognize more cameras without creating conflicts.
> [sensorDB] allow partial match of "Make" value in metadata

- src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
The threshold was oversized, lower value improves performances without measurable quality impact.
> [sfm] LocalBA: reduce minimum number of images to use sparse BA

- src/aliceVision/mesh/Texturing.cpp
- src/aliceVision/mesh/UVAtlas.cpp
- src/aliceVision/mesh/UVAtlas.hpp
Fix infinite loop when charts are larger than final texture size.
Fix #395 
Apply downscale factor to fit larger charts into the texture, and use it when filling atlases and computing final UV textures.
> UVAtlas: downscale charts to fit in texture

- src/aliceVision/depthMap/SemiGlobalMatchingRc.cpp
- src/aliceVision/depthMap/SemiGlobalMatchingVolume.cpp
- src/aliceVision/depthMap/SemiGlobalMatchingVolume.hpp
- src/aliceVision/fuseCut/DelaunayGraphCut.cpp
- src/aliceVision/mvsUtils/MultiViewParams.hpp
3 similarity volumes are now exported with debug option `exportIntermediateResults`:
- similarity volume before reduction
- similarity volume after reduction
- similarity volume after filtering
> [depthMap] Add similarity volumes debug export

- src/aliceVision/mvsData/image.cpp
- src/aliceVision/mvsData/image.hpp
- src/aliceVision/mvsUtils/MultiViewParams.cpp
Currently when DepthMap looks for the undistorted images It only checks if a file named as the view ID is inside the folder. It's better to also check that the extension is one of the supported files to avoid possible ambiguities with other files (especially if not using the UID as ID).
> [mvs] make search for undistorted images more robust

- src/aliceVision/depthMap/RefineRc.cpp
Fix https://github.com/alicevision/meshroom/issues/409
A bug on depth map computation has been introduced in AliceVision-2.1.0 release (corresponding to Meshroom-2019.1).
This problem only happens when badly connected cameras have been reconstructed in the SfM.
The function "refinerc" do not deal with files anymore. The file manipulation has been moved to a more high-level function. Unfortunately, one early-exit condition has not been updated during this refactoring. This PR fixes this mistake.
> [depthMap] fix crash if no nearby camera

- src/aliceVision/sfm/BundleAdjustmentCeres.hpp
Without this change, on a platform without OpenMP (and `ALICEVISION_USE_OPENMP` set to `OFF`), I get the compilation error:
```
In file included from /tmp/alicevision-20190320-90096-e7um3x/AliceVision-2.1.0/src/aliceVision/sfm/sfm.hpp:15:
/tmp/alicevision-20190320-90096-e7um3x/AliceVision-2.1.0/src/aliceVision/sfm/BundleAdjustmentCeres.hpp:35:35: error: use of undeclared identifier 'omp_get_max_threads'
, nbThreads(multithreaded ? omp_get_max_threads() : 1) // set number of threads, 1 if OpenMP is not enabled
^
```
> BundleAdjustmentCeres should #include alicevision_omp.hpp

- src/aliceVision/depthMap/CMakeLists.txt
- src/aliceVision/mvsUtils/CMakeLists.txt
Add missing dependencies in  `depthMap` module.
> [depthMap] add missing dependencies to sfmData/sfmDataIO modules

- src/aliceVision/depthMap/RefineRc.cpp
- src/aliceVision/depthMap/cuda/PlaneSweepingCuda.cpp
- src/aliceVision/mesh/Texturing.cpp
- src/aliceVision/mesh/Texturing.hpp
- src/aliceVision/mvsData/Color.hpp
- src/aliceVision/mvsUtils/ImagesCache.cpp
- src/aliceVision/mvsUtils/ImagesCache.hpp
- src/aliceVision/mvsUtils/fileIO.cpp
[X] Contribution to multiple textures per image. It limits the number of images reloads from files. Around 3x speedup on a dataset of 250 images.
[X]  Texture padding speedup: Create the padding with only `2` loops over the texture instead of
`2*padding` loops. So the performance cost does not depend on the size of the padding anymore. 28% speedup on a small dataset of 12 images. Of course, the speedup be smaller on large datasets as the largest part of the processing will be the image contributions.
> [mesh]  texturing: performance optimization of image fusion

- src/aliceVision/matchingImageCollection/geometricFilterUtils_test.cpp
- src/aliceVision/sfm/LocalBundleAdjustmentGraph.cpp
- src/aliceVision/sfm/LocalBundleAdjustmentGraph.hpp
- src/aliceVision/sfm/bundleAdjustment_test.cpp
- src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
This PR fixes management of intrinsics related connections in the local bundle adjustment graph which could lead to removal of wrong edges and potential corruption of the graph. This could end up with the SfM going in an infinite loop and/or undefined behavior.
Internal data structure containing edge IDs by intrinsic (`_intrinsicEdgesId`) is now properly updated to match changes in the underlying lemon graph when a view is removed from it. This avoids removing wrong edges (leading to potential corruption of the graph) when locking an intrinsics.
> Fix LocalBA intrinsics edges management

- src/aliceVision/matching/ArrayMatcher_kdtreeFlann.hpp
- src/aliceVision/matching/RegionsMatcher.hpp
We store the matching distance score when ALICEVISION_DEBUG_MATCHING is enabled.
This PR fix the indexes used for retrieving the distance value.
> [matching] fix debug distance value

- src/aliceVision/feature/akaze/AKAZE.cpp
Sort keypoints by size to guarantee best points are kept. Reordering keypoints also helps preventing grid-filtering from creating a non-uniform distribution within cells when input keypoints are sorted by spatial coordinates.
**Before**
**After**
> AKAZE: sort keypoints by size before grid filtering

- src/aliceVision/sensorDB/cameraSensors.db
Corrected the make of following models -> Nokia; Nokia 7 plus/6/3 to HMD Global; Nokia 7 plus/6/3
Meshroom shows a warning telling to add HMD Global; Nokia 7 plus/6/3 lens widths to the database, fixed by changing the make of refrenced models to HMD Global.
=====================================================================
> Correction to manufacturer

- src/aliceVision/matching/indMatch_test.cpp
- src/aliceVision/matching/io.cpp
- src/aliceVision/matching/io.hpp
- src/aliceVision/sfm/pipeline/regionsIO.cpp
- src/aliceVision/sfmData/CMakeLists.txt
- src/aliceVision/sfmData/SfMData.cpp
- src/aliceVision/sfmData/SfMData.hpp
- src/aliceVision/sfmData/sfmData_test.cpp
- src/software/pipeline/main_featureMatching.cpp
- src/software/pipeline/main_globalSfM.cpp
- src/software/pipeline/main_incrementalSfM.cpp
Introduce an automatic prefix system for matches files when using "range" command-line parameters. The goal of this PR is to ensure a file created for one iteration does not get overwritten in another one.
When generating matches files per image, we rely on minimal viewId of each image pair to create the filename (minViewId.txt). By iterating over sorted viewIds which only match with greater viewIds, this guarantees that files are written only once. 
However, the latter condition can be broken in the current pipeline when the file generated by the ImageMatching step declares for one view [B] a match with a view [A] that has an inferior viewId. This occurs when [A] has reached max view matches; the [A,B] view match is moved to [B]. If [A] and [B] are handled in two distinct iterations (1) …
> FeatureMatching: Prefix output matches files when using "ranges" to avoid overwrites

- src/software/export/CMakeLists.txt
Remove uneeded `exportColoredPointCloud` dependency to `aliceVision_mesh`
Fix SfM build without the MVS part.
> [software] exportColoredPointCloud: remove uneeded dependency to 'mesh'

- src/aliceVision/image/io.cpp
- src/aliceVision/imageIO/image.cpp
Follow the changes in oiio to manage colorspaces on RAW images, see: https://github.com/OpenImageIO/oiio/pull/2260
And deal with compatibility with previous oiio versions.
> [imageIO] ask "Linear" colorspace for RAW images

- src/aliceVision/image/io.cpp
- src/aliceVision/imageIO/image.cpp
Remove duplicated log line that is outside the color conversion operation.
> [image] io: remove erroneous log in  sRGB conversion

- src/aliceVision/mesh/Texturing.cpp
Fix error in the calculus of uv coordinates for UDIM format. Non-null integer values are now written at 1 in the texture atlas (and no more at 0).
> [mesh] fix uv coordinates for UDIM format

- src/aliceVision/depthMap/DepthSimMap.cpp
- src/aliceVision/fuseCut/Fuser.cpp
Remove remaining image transposition in the MVS part (Fuser and DepthSimMap).
> [depthMap] [fuseCut] remove image transposition

- src/aliceVision/mesh/Mesh.cpp
- src/aliceVision/mesh/Mesh.hpp
- src/aliceVision/mesh/MeshClean.cpp
- src/software/pipeline/main_meshFiltering.cpp
- src/software/pipeline/main_meshing.cpp
This PR adds vertex color data in Mesh class, with OBJ file format IO support. Regarding software, vertex colors are written in Meshing step's output OBJ file and correctly preserved during MeshFiltering.
Vertex colors are written as 3 additional floats per vertex line in OBJ files. It is not part of the official OBJ file format description but it is supported by several software.
From: https://en.wikipedia.org/wiki/Wavefront_.obj_file#Geometric_vertex
> A vertex can be specified in a line starting with the letter v. That is followed by (x,y,z[,w]) coordinates. W is optional and defaults to 1.0. Some applications support vertex colors, by putting red, green and blue values after x y and z. The color values range from 0 to 1.
> Vertex-colored meshes

- src/software/convert/main_convertSfMFormat.cpp
Enable to use simple regular expressions in the image white list of the ConvertSfMFormat.
For instance, it enables to keep only the images starting with "IMG_" in their filename using the following filter: ```*/IMG_*```.
> [software] ConvertSfMFormat: allow regex in image white list

- src/CMakeLists.txt
- src/aliceVision/dataio/VideoFeed.cpp
- src/aliceVision/fuseCut/Fuser.cpp
Fix iteration over tcdepthmap in filterGroupsRC - Solve segmentation fault in DepthMapFiltering when using images of different sizes
> [fusecut] fix iteration over tcdepthmap in filterGroupsRC

- src/aliceVision/depthMap/RefineRc.cpp
- src/aliceVision/depthMap/SemiGlobalMatchingRc.cpp
- src/aliceVision/depthMap/SemiGlobalMatchingRc.hpp
- src/aliceVision/depthMap/SemiGlobalMatchingVolume.cpp
- src/aliceVision/depthMap/SemiGlobalMatchingVolume.hpp
In particular configurations (failed to find Tc cameras), `sgmrc` can stop early before allocating the `_volumeBestIdVal`, which is later used in the refine step.
This bug fix in combination with #616 and #642, should fix the issues reported in https://github.com/alicevision/meshroom/issues/504, https://github.com/alicevision/meshroom/issues/481, https://github.com/alicevision/meshroom/issues/458, https://github.com/alicevision/meshroom/issues/431, https://github.com/alicevision/meshroom/issues/425.
> [depthMap] bug fix: use RAII instead of pointers

- CMakeLists.txt
- Dockerfile
> Fixes to the all-in-one build

- src/aliceVision/sfmDataIO/AlembicImporter.cpp
Fixing errors related to Alembic built with boost.
When Alembic is configured to use boost it creates an alias for `shared_ptr` from boost library. This causes compilation error, `std::shared_ptr` can not be converted to `boost::shared_ptr`.
Instead of relying explicitly on the `std::shared_ptr` type, we can use an alias from `Alembic::Abc::IDoubleArrayProperty::sample_ptr_type`.
> std::shared_ptr replaced with `IDoubleArrayProperty::sample_ptr_type` alias

- src/aliceVision/sensorDB/cameraSensors.db
Updated the camera sensor database file with values for the two versions of RaspberryPi cameras. The sensor width values are derived from the sensor device datasheets:
v1 (OmniVision OV5647): 2592 active pixels * 1.4 micron unit cell size
v2 (Sony IMX219): 3280 active pixels * 1.12 micron unit cell size
> Update camera sensor database for RaspberryPi cameras

- CMakeLists.txt
- Dockerfile
Go back to cuda-7.0 to create binaries to reduce incompatibilities.
Use a specific commit in CCTag to avoid runtime incompatibilities.
> Build fixes included in the binaries of the release 2.2.0

- src/aliceVision/feature/cctag/ImageDescriber_CCTAG.hpp
- src/aliceVision/feature/imageDescriberCommon.hpp
- src/aliceVision/mesh/Texturing.cpp
- src/aliceVision/sfm/CMakeLists.txt
- src/aliceVision/sfm/pipeline/ReconstructionEngine.cpp
- src/aliceVision/sfm/pipeline/ReconstructionEngine.hpp
- src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
- src/aliceVision/sfm/utils/alignment.cpp
- src/aliceVision/sfm/utils/alignment.hpp
- src/aliceVision/sfmData/SfMData.hpp
- src/software/pipeline/main_incrementalSfM.cpp
- src/software/utils/CMakeLists.txt
- src/software/utils/main_sfmAlignment.cpp
- src/software/utils/main_sfmTransfer.cpp
- src/software/utils/main_sfmTransform.cpp
Use CCTag markers to define the coordinate system: the SfMTransform node provides new inputs to align specific markers to known 3D positions.
Markers IDs are stored in the landmark color to avoid the creation of an additional field which would take space for nothing on all landmarks. Maybe in the future, we could consider to have multiple types of landmarks (with different data structure) but that would represent a complex change for a limited benefit for now.
> Coordinate system alignment to specific markers or between scenes

- src/aliceVision/prettyprint.hpp
Would be nice to avoid this workaround with a proper fix: https://github.com/louisdx/cxx-prettyprint/issues/30
But for now, it allows to build on windows.
> Workaround for a build incompatibility between prettyprint and eigen

- src/aliceVision/sensorDB/cameraSensors.db
My OnePlus 5T write the model data as A5010 in the `EXIF` metadata. Add this missing entry to the database.
> Add Oneplus 5T sensor width to the database

- src/aliceVision/sensorDB/cameraSensors.db
The previous infos for LG G6's camera sensors didn't work for me. I searched my camera sensors info and I noticed that the phone saves photos with this format in metadata, and when tested it worked, so I added them.
> Added working infos in LG G6 camera sensors

- src/aliceVision/mvsUtils/MultiViewParams.cpp
min/maxDepth in depth maps metadata should be optional
> [meshing] fix load of depth maps without metadata

- src/aliceVision/keyframe/KeyframeSelector.cpp
- src/aliceVision/keyframe/KeyframeSelector.hpp
Needed to use the sequential method: https://github.com/alicevision/AliceVision/pull/730
> [keyframe] KeyframeSelector: add padding in created filenames

- src/aliceVision/image/io.cpp
Fix bug with input RGBA Images.
Alpha channel was erased on image reading.
> [image] Fix bug with input RGBA Images

- src/aliceVision/sensorDB/cameraSensors.db
Adding [dji mavic mini](https://www.dji.com/mavic-mini/specs) to camera db
N/A
~~I'm not sure why this message shows up, the exif data looks fine for this image.~~
**Edit:**
The previous DJI entries have a slightly different naming convention for the model. I incorrectly assumed it would be the same. I have updated the pr in a second commit to exactly match the model name produced by the camera sensor.
```
[10:37:33.425887][warning] The camera found in the database is slightly different for image(s):
[10:37:33.426051][warning] image: 'DJI_0020.JPG'
- image camera brand: DJI
- image camera model: FC7203
- database camera brand: DJI
- database camera model: DJI FC7203
- database camera sensor size: 6.16 mm
[10:37:33.426159][warning] Please check and correct camera model(s) name in the …
```
> dji updates + cameradb update

- src/aliceVision/sfm/pipeline/global/GlobalSfMTranslationAveragingSolver.cpp
- src/aliceVision/sfm/pipeline/global/ReconstructionEngine_globalSfM.cpp
- src/aliceVision/sfm/pipeline/structureFromKnownPoses/StructureEstimationFromKnownPoses.cpp
- src/aliceVision/track/Track.hpp
- src/aliceVision/track/track_test.cpp
- src/software/export/main_exportTracks.cpp
Replace https://github.com/alicevision/AliceVision/pull/748
> Fix tracks filtering

- INSTALL.md
Looks like the docker build command that was provided earlier should have been for the earlier version of Dockers, I'm using Docker version 19.03.8 and copying the above command doesn't work. Since in the newer version of docker, the --build-arg needs to be added separately for each param.
> Minor Changes in the docker build command

- src/aliceVision/sensorDB/cameraSensors.db
Added sensor database entry for Samsung Galaxy Note9, calculated from the vendor-provided specifications for the rear wide-angle camera.
Calculated based on the camera's maximum resolution of 4032px x 3024px and Samsung's stated sensor pixel size of 1.4µm.
> Added sensor database entry for Samsung Galaxy Note9

- CMakeLists.txt
- Dockerfile
- Dockerfile_deps
- docker-build.sh
Update cmake all-in-one build to install all third parties in the same folder directly.
Split the Docker in 2 parts, so we dont need to rebuild all dependencies to update AliceVision changes.
Update the following libraries:
- cctag
- popsift
- lapack3.9.0
- suitesparse-5.6.0
- ceres
- openexr-2.4
- tiff-4.1.0
- turbojpeg-2.0.4
- libraw-0.19.5+patch
- boost-1.70
- alembic-1.7.12,
- geogram-1.7.4
- oiio-2.1.12
> Release docker

- appveyor.yml
> [setup appveyor to release windows binaries from the develop branch](https://github.com/alicevision/AliceVision/issues/392#issuecomment-392254832)
For every commit, a snapshot build for windows can be downloaded from the [appveyor build artifacts tab](https://ci.appveyor.com/project/AliceVision/alicevision/build/artifacts).
Details: https://www.appveyor.com/docs/packaging-artifacts/
**Note**: (_to be added to the wiki_)
Do not use snapshots if you need a stable version.
Snapshot builds are for developers and testers and should be considered unstable.
With snapshots, users can test and report back on a bugfix/feature without waiting for the official release or needing to build alicevision on their own.
> [appveyor] build alicevision snapshot binaries (win)

- src/aliceVision/sensorDB/sensorDatabaseSort.py
In Python3 `basestring` was removed and replaced with `str`. So I replaced them.
> Replace deprecated basestring with str (Py3)

- src/aliceVision/calibration/CMakeLists.txt
- src/aliceVision/dataio/CMakeLists.txt
- src/aliceVision/feature/CMakeLists.txt
- src/aliceVision/fuseCut/CMakeLists.txt
- src/aliceVision/image/io.cpp
- src/aliceVision/image/io.hpp
- src/aliceVision/localization/CMakeLists.txt
- src/aliceVision/matching/CMakeLists.txt
- src/aliceVision/mesh/CMakeLists.txt
- src/aliceVision/mvsData/CMakeLists.txt
- src/aliceVision/mvsUtils/CMakeLists.txt
- src/aliceVision/sensorDB/CMakeLists.txt
- src/aliceVision/sfm/CMakeLists.txt
- src/aliceVision/sfmData/CMakeLists.txt
- src/aliceVision/sfmDataIO/CMakeLists.txt
- src/aliceVision/system/CMakeLists.txt
- src/aliceVision/voctree/CMakeLists.txt
A quick fix for missing dependency from `Boost::boost` in some modules.
Because some header-only boost components are used we should also explicitly link with `Boost::boost`
> [cmake] missing Boost::boost dependency

- src/cmake/FindOpenEXR.cmake
> [cmake] fix findOpenEXR missing " escapes

- .github/workflows/continuous-integration.yml
> [ci] Add github actions CI

- src/aliceVision/sensorDB/cameraSensors.db
https://github.com/alicevision/AliceVision/issues/789
~70 new models:
- Meizu 2019/20 models
- LG 2019/20 models
- Vivo 2020 models
- Hasselblad
:star: 7004 camera models are now in the SensorDB
> SensorDB new models

- src/aliceVision/matching/kvld/algorithm.cpp
- src/aliceVision/matching/kvld/algorithm.h
- src/aliceVision/matching/kvld/kvld.cpp
- src/aliceVision/matching/kvld/kvld.h
Fix https://github.com/alicevision/AliceVision/issues/778
> [matching] build fix for MSVC 2019

- INSTALL.md
While building on my machine (Linux - Ubuntu 18.04) I ran into the prompt `CMake 3.11 or higher is required.` when running `cmake` for the first time. I have changed the required CMake version in the isntallation instructions to reflect the new tool version requirement.
Please let me know if I need to update anything else in the file to reflect my new change.
@flosincapite please review.
> update required CMake version

- CONTRIBUTING.md
- src/aliceVision/matching/io.cpp
- src/aliceVision/matching/io.hpp
There were several functions that had a different signature declaration between declaration and definition. (i.e. some API were not implemented)
> [Matching] fix unmatching declaration and definitions

- src/aliceVision/feature/ImageDescriber.hpp
- src/aliceVision/feature/akaze/ImageDescriber_AKAZE.hpp
- src/aliceVision/feature/cctag/ImageDescriber_CCTAG.cpp
- src/aliceVision/feature/cctag/ImageDescriber_CCTAG.hpp
- src/aliceVision/feature/openCV/ImageDescriber_AKAZE_OCV.hpp
- src/aliceVision/feature/sift/ImageDescriber_SIFT.hpp
- src/aliceVision/feature/sift/ImageDescriber_SIFT_popSIFT.cpp
- src/aliceVision/feature/sift/ImageDescriber_SIFT_popSIFT.hpp
- src/aliceVision/feature/sift/ImageDescriber_SIFT_vlfeat.hpp
- src/aliceVision/feature/sift/ImageDescriber_SIFT_vlfeatFloat.hpp
- src/software/pipeline/main_featureExtraction.cpp
Since alicevision/popsift/pull/71, popsift is now always releasing the resources with the destructor.
In our implementation of `ImageDescriber_SIFT_popSIFT` popsift is a static member of the class to avoid multiple instances of the Cuda run-time.
Since static object are destroyed last, it happens in `alicevision_extractFeatures` that the popsift destructor tries to release resource when the Cuda runtime is already shut down.
This causes an error on exit from the program:
```
~/dev/alicevision/sandbox/popsift/src/popsift/s_image.cu:259
Could not destroy texture object: driver shutting down
```
In order to fix the problem, a static counter in the class `ImageDescriber_SIFT_popSIFT` has been added to count how many instances of the class there are and when the last one is destroyed, also the …
> [bug] fix popsift static release

- CMakeLists.txt
- Dockerfile_ubuntu
- Dockerfile_ubuntu_deps
fixes #718 
Update the dockerfile for ubuntu:
* split in deps and main like centos
* use latest cmake version
* some fixes in the cmake (dependency script)
* use `<SOURCE_DIR>` for opencv
* install license and other AV doc file only when installing AV
> [Docker] fix ubuntu dockerfile

- src/aliceVision/sfmData/CMakeLists.txt
- src/aliceVision/sfmData/View.cpp
- src/aliceVision/sfmData/View.hpp
- src/aliceVision/sfmData/uid.cpp
- src/aliceVision/sfmData/view_test.cpp
- src/aliceVision/sfmDataIO/AlembicExporter.cpp
- src/aliceVision/sfmDataIO/viewIO.cpp
- src/software/export/main_exportAnimatedCamera.cpp
- src/software/pipeline/main_cameraInit.cpp
Recognize images with non standard metadata as exported by Nuke on EXR images.
Replace https://github.com/alicevision/AliceVision/pull/777
> More generic metadata support

- src/aliceVision/camera/PinholeBrown.hpp
- src/aliceVision/camera/PinholeFisheye.hpp
- src/aliceVision/camera/PinholeFisheye1.hpp
- src/aliceVision/camera/PinholeRadial.hpp
- src/aliceVision/camera/camera.hpp
- src/aliceVision/camera/cameraCommon.hpp
- src/aliceVision/sfm/BundleAdjustmentCeres.cpp
- src/aliceVision/sfm/bundleAdjustment_test.cpp
- src/aliceVision/sfm/pipeline/global/globalSfM_test.cpp
- src/aliceVision/sfm/pipeline/sequential/sequentialSfM_test.cpp
- src/aliceVision/sfm/utils/syntheticScene.cpp
- src/aliceVision/sfmDataIO/AlembicImporter.cpp
- src/aliceVision/sfmDataIO/jsonIO.cpp
- src/aliceVision/sfmDataIO/jsonIO.hpp
- src/aliceVision/sfmDataIO/viewIO.cpp
- src/aliceVision/sfmDataIO/viewIO.hpp
- src/software/pipeline/main_cameraInit.cpp
> [cameraInit] Support more extensions and add new viewId generation method

- src/software/utils/main_imageProcessing.cpp
Use Premult to ensure that the fill holes works as expected
> [software] imageProcessing: fix fillHoles behaviour

- src/aliceVision/fuseCut/DelaunayGraphCut.cpp
> [fuseCut] Similarity map is optional

- src/aliceVision/colorHarmonization/CommonDataByPair.hpp
- src/aliceVision/colorHarmonization/gainOffsetConstraintBuilder_test.cpp
- src/aliceVision/dataio/ImageFeed.cpp
- src/aliceVision/image/convertion.hpp
- src/aliceVision/mvsUtils/MultiViewParams.cpp
- src/aliceVision/sfm/generateReport.cpp
- src/aliceVision/sfm/pipeline/global/GlobalSfMRotationAveragingSolver.cpp
- src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
- src/aliceVision/sfm/sfmStatistics.cpp
- src/aliceVision/sfm/sfmStatistics.hpp
- src/aliceVision/sfmDataIO/viewIO.cpp
- src/aliceVision/sfmDataIO/viewIO.hpp
- src/aliceVision/utils/CMakeLists.txt
- src/aliceVision/utils/Histogram.hpp
- src/aliceVision/utils/filesIO.hpp
- src/aliceVision/utils/regexFilter.hpp
- src/aliceVision/utils/regexFilter_test.cpp
- src/software/convert/main_convertSfMFormat.cpp
- src/software/export/main_exportAnimatedCamera.cpp
- src/software/pipeline/main_prepareDenseScene.cpp
- src/software/utils/main_imageProcessing.cpp
- src/software/utils/precisionEvaluationToGt.hpp
- src/software/utils/sfmColorHarmonize/colorHarmonizeEngineGlobal.cpp
> [software] imageProcessing: metadata feature

- src/software/pipeline/main_panoramaInit.cpp
Updates to the fisheye circle detection
> [software] PanoramaInit: fix bug in the estimation of the fisheye circle

- src/aliceVision/sfm/BundleAdjustmentCeres.cpp
- src/aliceVision/sfm/BundleAdjustmentCeres.hpp
- src/aliceVision/sfm/ResidualErrorFunctor.hpp
Ceres accepts a ParameterBlockOrdering hint which must assign
every parameter block to exactly one group.
BundleAdjustmentCeres can be called multiple times, and on each
call resetProblem() is called internally to clear the parameter blocks.
However, resetProblem() did not clear the ParameterBlockOrdering.
If the BundleAdjustmentCeres object was used more than once,
Ceres would fail with an error.
In practice, the BundleAdjustmentCeres object is used in a loop that
repeatedly calls adjust() while removing outliers on each iteration.
If the first iteration succeeded with no outliers, the loop would
correctly exit. However, if any outliers are present, the entire
bundle adjustment routine fails leading to the warning:
"Bundle Adjustment failed, the solution is not usable."
This incorrect …
> [SfM] Major bug fix on BlockOrder in BACeres

- src/software/pipeline/main_meshing.cpp
- src/software/utils/main_sfmTransform.cpp
New input transformation type for computing the Bounding Box (reconstruction area) based on translation, rotation and scale.
Rotation is based in Euler angles (ZXY).
```bash
--boundingBox tx,ty,tz,rx,ry,rz,sx,sy,sz
```
New input transformation type to translate, rotate and scale the SfM. Rotation is based in Euler angles (ZXY). Scale is uniform.
```bash
--method manual --manualTransform tx,ty,tz,rx,ry,rz,s
```
> [software] Meshing & SfMTransform : new input transformation type

- src/software/pipeline/main_panoramaInit.cpp
When the input image is not correctly rotated according to xml
> [software] PanoramaInit: Add an extra image rotation to each camera declared the input xml

- src/aliceVision/camera/IntrinsicBase.hpp
- src/aliceVision/sfm/sfmFilters.cpp
- Use greedy hueristic to avoid O(N^2) code in vast majority of cases
- Use Eigen matrix operations to speed up O(N^2) operations
- Add omp parallel
This diff removes an N^2 loop which becomes relevant when processing large numbers of images. On my setup, when processing 8000 images 50% of the time is spent in this routine.
The loop in question searches for the largest angle between view directions. In my implementation, I first attempt a simple greedy algorithm which in almost all cases exits in sub-linear time if the angle exists. If the greedy algorithm fails, I revert to a n^2 implemented in Eigen for speed..
I haven't done a thorough analysis, but I suspect the overall expected runtime is << linear.
> [sfm] Performance improvements: optimize RemoveOutliers_AngleError

- src/aliceVision/sfmData/View.cpp
- src/aliceVision/sfmData/View.hpp
- src/software/pipeline/main_LdrToHdrCalibration.cpp
- src/software/pipeline/main_LdrToHdrMerge.cpp
HDR fusion did not work when using multiple brackets with variable ISO and/or Aperture.
This PR updates the equations used.
> Update compensation of aperture and ISO change in HDR fusion

- src/aliceVision/sensorDB/cameraSensors.db
Add Moto Z (2) to camerasensors.db.
Added a missing entry to cameraSensors.db
This is my first time doing this.
On each installation of meshroom I add this to the DB file so it functions with my phone, it would be nice if this were part of the standard program.
> Add entry to cameraSensors.db

- src/aliceVision/sfmDataIO/sfmDataIO.cpp
fix https://github.com/alicevision/meshroom/issues/890
> [sfmDataIO] throw if we try to load an abc file and AliceVision is built without Alembic support

- src/aliceVision/hdr/hdrMerge.cpp
- src/aliceVision/image/io.cpp
- src/aliceVision/image/io.hpp
- src/software/pipeline/main_LdrToHdrMerge.cpp
- src/software/pipeline/main_panoramaCompositing.cpp
- src/software/pipeline/main_panoramaWarping.cpp
> HDR Panorama: Handle very high intensities

- src/aliceVision/image/io.cpp
- src/software/utils/main_imageProcessing.cpp
> [software] ImageProcessing: add storageDataType option

- src/software/pipeline/main_panoramaInit.cpp
Put back lost features about multiple maximas in the radius image.
> [software] PanoramaInit: improve fisheye circle detection

- src/aliceVision/hdr/DebevecCalibrate.cpp
- src/software/pipeline/main_LdrToHdrCalibration.cpp
- src/software/pipeline/main_imageMatching.cpp
Debevec calibration needs an additional constraint to fix a degree of freedom.
We previously used that f(1) = 0 for all channels. But this caused problem on some dataset as the maximal value is different between channels.
This PR use f(0.5) = 0, which is the original constraint (as per the paper). We used f(1) = 0 for numerical stability in some tests.
This is a major update to the debevec update. All sequences should be tested.
> [HDR] Update the scale constraint

- src/aliceVision/mesh/Texturing.cpp
Fixed reference after null crash on texturing replaceMesh method called when not using a basic unwrap.
- [ X] Fixes https://github.com/alicevision/meshroom/issues/1107
Introduced in diff between 2.3.0 & 2.2.0
> Texturing segfault fix

- src/aliceVision/sensorDB/cameraSensors.db
Multiple LG G4 were tested and for each of them the model and
manufacturer were named as in this commit. Since I don't know whether
the model and manufacturer names are version related, I keep the old
sensor description to avoid issues for other users.
See https://github.com/alicevision/AliceVision/issues/906
> [sensorDB] Add another LG G4 sensor description

- src/CMakeLists.txt
- src/aliceVision/image/io.cpp
inSpec was a reference to a potentially destroyed object (std::swap inside the braces)
> [image] Remove reference to potentially destroyed object

- src/aliceVision/fuseCut/DelaunayGraphCut.cpp
- src/aliceVision/fuseCut/DelaunayGraphCut.hpp
- src/software/pipeline/main_meshing.cpp
Added a new parameter (minVis) in the graph cut step in order to filter out points with observation < minVis. 
New parameter for the meshing node of the reconstruction pipe. 
I think the implementation is trivial however I am not sure the new parameter should have been referenced elsewhere in the code (I know it should be added to meshroom API).
> [fuseCut] added a parameter to filter points based on number of observations

- src/aliceVision/sensorDB/cameraSensors.db
[Samsung Note9 (SM-N960F - Wide Camera)](https://www.phonemore.com/specs/samsung/galaxy-note-9/sm-n960fds-128gb/)
Resolution: 4032x3024 pixels
Sensor Size: 1/2.55"
Pixel Size: 1.4µm
Sensor Width: 4032 * 1.4µm = **5.6448mm**
I'm not sure how to add the separate telephoto sensor.
> Update cameraSensors.db - Added Samsung Note9 (SM-N960F - Wide Camera)

- src/aliceVision/image/Image.hpp
- src/aliceVision/image/pixelTypes.hpp
- src/aliceVision/lightingEstimation/lightingEstimation.cpp
- src/aliceVision/lightingEstimation/lightingEstimation.hpp
- src/aliceVision/lightingEstimation/lightingEstimation_test.cpp
- src/aliceVision/robustEstimation/randSampling.hpp
- src/software/utils/CMakeLists.txt
- src/software/utils/main_lightingEstimation.cpp
Estimate Spherical Harmonics from normal maps and albedo maps.
This is a low-level preliminary work and not a new feature for end-users.
> Lighting estimation software

- src/aliceVision/sfmData/SfMData.cpp
Canonical path on internal sfmData path should not throw an error.
> Support for unavailable folder in sfmData

- src/aliceVision/fuseCut/DelaunayGraphCut.cpp
- src/aliceVision/fuseCut/DelaunayGraphCut.hpp
- src/aliceVision/fuseCut/DelaunayGraphCut_test.cpp
- src/aliceVision/fuseCut/delaunayGraphCutTypes.hpp
- src/aliceVision/mesh/MeshAnalyze.cpp
- src/aliceVision/mesh/MeshAnalyze.hpp
- src/aliceVision/mvsData/Point2d.hpp
- src/aliceVision/mvsData/Point3d.hpp
- src/aliceVision/mvsData/Point4d.hpp
- src/aliceVision/mvsData/geometry.cpp
- src/aliceVision/mvsData/geometry.hpp
- src/aliceVision/mvsUtils/common.cpp
- src/aliceVision/mvsUtils/common.hpp
- src/software/pipeline/main_meshing.cpp
With the improvements of the tetrahedral intersection in https://github.com/alicevision/AliceVision/pull/848, some adjustments are needed in the next steps.
ones along the ray from the 3D vertex to the camera. The tetrahedral intersection now works fine and reach the camera almost all the time, so only the tetrahedra around the camera were voting on cellSWeight. This creates problem on some datasets, so we now vote for multiple cells.
> [fuseCut] adjustments to the tetrahedral vote

- src/software/convert/CMakeLists.txt
- src/software/convert/main_convertMesh.cpp
- src/software/utils/CMakeLists.txt
- src/software/utils/main_mergeMeshes.cpp
Add two softwares based on Geogram for mesh boolean operations and mesh conversion.
> Add mesh utilities softwares

- src/aliceVision/mesh/Mesh.cpp
- src/aliceVision/mesh/Mesh.hpp
- src/software/pipeline/main_meshFiltering.cpp
Add smoothing and filtering options for MeshFiltering software.
> [software] MeshFiltering: smoothing and filtering options on subset of the geometry

- src/aliceVision/sensorDB/cameraSensors.db
Xiaomi;Xiaomi Mi A2;4.96;devicespecifications
Xiaomi Mi A2 has rear camera with a sensor (Sony IMX486 Exmor RS ) format of 1/2.9'' meaning (~ 4.96 x 3.72 mm)
sources:
https://www.devicespecifications.com/en/model/00354b63
https://www.digicamdb.com/sensor-sizes/
> Update cameraSensors.db with Xiaomi Mi A2

- src/aliceVision/fuseCut/DelaunayGraphCut.cpp
- src/aliceVision/fuseCut/DelaunayGraphCut.hpp
- src/aliceVision/fuseCut/DelaunayGraphCut_test.cpp
- src/aliceVision/mvsUtils/common.cpp
- src/aliceVision/mvsUtils/common.hpp
- src/software/pipeline/main_meshing.cpp
Add option in Meshing, for digging using shape from silhouette principle.
Warning: may have an impact on the tetrahedral vote due to the change in the usage of a global `pixSize` per vertex (for all observations/cameras) instead of a value per view.
> [meshing] Digging using shape from silhouette principle

- CMakeLists.txt
- ci/install-dependencies.sh
Update OpenImageIO to 2.2.11.1. Version 2.2.11 supports HEIF and AVIF files, when build with libheif >= 1.7.
In the future, build OpenImageIO with libheif.
> Deps: Update OpenImageIO to 2.2.11.1

- src/aliceVision/mesh/Texturing.cpp
Avoid possible crashes due to excessive memory usage.
Reaching memory limits could crash the Texturing step:
With the modified estimation:
And with uniform repartition:
> [software] Texturing: improve memory usage

- src/aliceVision/fuseCut/DelaunayGraphCut.cpp
Avoid infinit loops in particular configurations.
> [fuseCut] intersectNextGeom: add explicit direction test

- src/aliceVision/matchingImageCollection/ImageCollectionMatcher_generic.cpp
- src/aliceVision/matchingImageCollection/ImageCollectionMatcher_generic.hpp
- src/aliceVision/matchingImageCollection/matchingCommon.cpp
- src/aliceVision/matchingImageCollection/matchingCommon.hpp
- src/software/pipeline/main_featureMatching.cpp
Add cross check for feature matching : 
For an image pair (I, J). 
If a keypoint a in I match to a keypoint b in J, then this match is accepted if and only if keyboint b in J match to keypoint a in I.
> [matching] implement cross check for feature matching

- src/aliceVision/camera/cameraUndistortImage.hpp
- src/aliceVision/image/io.cpp
- src/aliceVision/image/io.hpp
- src/software/export/main_exportAnimatedCamera.cpp
- We want to export the transformation map between the origin image and the undistorted one.
- The undistorted image must contain a ROD which includes all the available pixels
> Export distortion map in exr format

- src/cmake/OptimizeForArchitecture.cmake
Update the OptimizeForArchitecture so that Intel i9-10900K is recognized.
(do we really need this? the whole file is quite outdated...)
Info from here https://en.wikichip.org/wiki/intel/microarchitectures/comet_lake#Compiler_support
> [cmake] update flags for Intel i9-10900K

- src/aliceVision/sensorDB/cameraSensors.db
https://en.wikipedia.org/wiki/Samsung_CMOS -> calculated (estimated) sensor width would be 9.6 
Sensor width as provided by https://www.devicespecifications.com/en/model/c29352e7
is 10.82 mm
Closes request by @Faceless-Fan - you can add the following lines to your sensordatabase:
please comment if your images are detected now.
Samsung;Samsung Galaxy S20 Ultra 5G Exynos;10.82;devicespecifications
Samsung;Samsung SM-G988;10.82;devicespecifications
Samsung;Samsung SM-G9880;10.82;devicespecifications
Samsung;Samsung SM-G988B/DS;10.82;devicespecifications
Samsung;Samsung SM-G988N;10.82;devicespecifications
> [sensorDB] Galaxy S20 Ultra 5G Exynos

- src/software/pipeline/main_panoramaEstimation.cpp
Automatic estimation of the reference frame for a panorama.
Assume all cameras (or at least, a large proportion) of the cameras have their X axis parallel to the ground.
> [panorama] automatic alignment of up vector

- src/aliceVision/feature/sift/ImageDescriber_DSPSIFT_vlfeat.cpp
Align parameters with "sift" feature type.
> [feature] dspsift: if image resolution is small, adjust first octave for extraction

- src/aliceVision/sfmDataIO/viewIO.cpp
This PR adds the camera model `PINHOLE_CAMERA` to the list of possible default camera models that can be chosen in `getViewIntrinsic()`. This change avoids the current error that is thrown when the user specifies "pinhole" as the only allowable camera model, yet this model cannot be chosen.
> [camera] Allow PINHOLE_CAMERA to be chosen as default model

- .github/workflows/continuous-integration.yml
- CMakeLists.txt
- docker/fetch.sh
- src/aliceVision/image/all.hpp
- src/aliceVision/image/convertionOpenCV.hpp
- src/software/utils/CMakeLists.txt
- src/software/utils/main_colorCheckerCorrection.cpp
- src/software/utils/main_colorCheckerDetection.cpp
- src/software/utils/main_imageProcessing.cpp
Color checker detection and Color checker corection nodes (beta)
> [software] New ColorChecker Detection and Correction

- src/aliceVision/sensorDB/cameraSensors.db
Simple user contribution do the sensorDatabase by adding the DJI Mavic Mini 2  camera info.
Tested using a 36 image dataset taken by a DJI Mavic Mini 2 for aerial photogrammetry.
> [MOD] Added new DJI FC7303 camera to src/aliceVision/sensorDB/cameraSensors.db

- src/software/export/main_exportAnimatedCamera.cpp
- Consider as video if we can extract a number in the filename. There is no correct way to classify between video and dslr. We prefer to have false-positives (detected as videos instead of dslr) than false-negatives.
- Export both distort and undistort UV maps
- Add an sfmDataFilter option to filter-out cameras from the photogrammetry
- Only export used intrinsics
> [software] Some adjustments to export animated camera

- src/aliceVision/hdr/rgbCurve.cpp
In gcc:11 `<numeric>` header no longer yields `<limits>` header.
https://gcc.gnu.org/gcc-11/porting_to.html#header-dep-changes
> GCC11: fix missing <limits> header.

- src/aliceVision/sensorDB/cameraSensors.db
Sensor is 1/2" as per:
- https://www.devicespecifications.com/en/model/51c75175
- https://www.gsmarena.com/xiaomi_mi_a3-9769.php
> Add Xiaomi A3 to cameraSensors.db

- src/aliceVision/sensorDB/cameraSensors.db
Following the tech spec from Asus:
https://www.asus.com/Mobile/Phones/ZenFone/Zenfone-8/techspec/
Sony IMX686 64 MP image sensor - 1/1.7" large sensor size, 0.8 µm pixel size.
For Asus Zenfone 8 - ZS590KS
I've tested it for me phone.
> [sensorDB] Add Asus Zenfone 8

- src/aliceVision/sfm/pipeline/regionsIO.cpp
- src/aliceVision/sfm/pipeline/regionsIO.hpp
- src/aliceVision/sfmDataIO/viewIO.cpp
- src/aliceVision/sfmDataIO/viewIO.hpp
- src/software/export/main_exportAnimatedCamera.cpp
- src/software/pipeline/main_cameraInit.cpp
This PR adds required features for the `QtAliceVision` plugin development.
> Add frameId from image path & new function for feature loading

- src/aliceVision/image/io.cpp
- src/aliceVision/image/io.hpp
- src/aliceVision/sfmDataIO/CMakeLists.txt
- src/aliceVision/sfmDataIO/middlebury.cpp
- src/aliceVision/sfmDataIO/middlebury.hpp
- src/aliceVision/sfmDataIO/middlebury_test.cpp
- src/software/utils/CMakeLists.txt
- src/software/utils/main_importMiddlebury.cpp
It introduces a new application to import the [Middlebury dataset ](https://vision.middlebury.edu/mview/data/)(dino, temple) as a alicevision sfmdata format (abc, sfm..).
It parses the .txt file of the dataset and outputs the relevant data file format of choice.
The images are supposed to be in the same folder as the .txt (as they are provided by the website)
Several options for the import
* the instrinsics (Pinhole model only as the images are already undistorted) can be locked or not, depending if one wants to benchmark the sfm part too
- Similarly the poses can be imported or not, and they can be locked or not
Example of the dense reconstruction for the temple full
> [sw] middlebury import

- src/aliceVision/sensorDB/cameraSensors.db
Added the Xiaomi POCOPHONE F3 with a sensor width of 6.4mm
> Added Xiaomi POCOPHONE F3

- src/aliceVision/numeric/CMakeLists.txt
- src/aliceVision/numeric/gps.cpp
- src/aliceVision/numeric/gps.hpp
- src/aliceVision/numeric/gps_test.cpp
- src/aliceVision/sfm/utils/alignment.cpp
- src/aliceVision/sfm/utils/alignment.hpp
- src/aliceVision/sfmData/SfMData.hpp
- src/aliceVision/sfmData/View.cpp
- src/aliceVision/sfmData/View.hpp
- src/aliceVision/sfmData/view_test.cpp
- src/software/utils/main_sfmTransform.cpp
It introduces another option to sfmTransform to align an existing sfmdata to the gps position available as exif metadata.
It computes the closest transformation that align the existing sfmdata to the GPS reference system (cartesian x,y,z ref system) 
* added functions to parse exif data to extract the gps position in cartesian reference system
* added methods to `View` to check for the gps data
* added option to sfmTransform to use gps data to align the scene
> GPS alignment from exif metadata

- src/aliceVision/mesh/Mesh.cpp
- src/aliceVision/mesh/Mesh.hpp
- src/aliceVision/mesh/Texturing.cpp
- src/aliceVision/mesh/Texturing.hpp
- src/aliceVision/mesh/meshVisibility.cpp
- src/aliceVision/mesh/meshVisibility.hpp
- src/aliceVision/mvsData/geometry.cpp
- src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
- src/software/convert/CMakeLists.txt
- src/software/convert/main_importKnownPoses.cpp
- src/software/pipeline/main_texturing.cpp
- src/software/utils/main_split360Images.cpp
- Import known poses from a JSON file (camera poses and intrinsics)
- Import known poses from XMP (XML) files (camera poses and intrinsics)
- Import known poses from a maya text file .ma (camera poses only).
- [mesh] new remap visibility method without dense sfmData information. Guess visibilities from mesh orientation. It assumes that there is no occultation from non reconstructed elements.
- [mesh] obj loader: fix material index management when combining multiple ones
- [sfm] incremental: optimize input when starting from known poses/landmarks
> New node to import known poses for various file formats

- src/aliceVision/mesh/Mesh.cpp
Replace remaining code which were still using a custom obj writer
> [mesh] Replacing custom code for mesh::saveToObj by using assimp library

- .gitignore
- src/aliceVision/fuseCut/DelaunayGraphCut.cpp
- src/aliceVision/mesh/Mesh.cpp
- src/aliceVision/mesh/Mesh.hpp
- src/aliceVision/mesh/MeshEnergyOpt.cpp
- src/aliceVision/mesh/Texturing.cpp
- src/aliceVision/mesh/Texturing.hpp
- src/aliceVision/mesh/meshPostProcessing.cpp
- src/aliceVision/mvsData/CMakeLists.txt
- src/aliceVision/mvsData/Point3d.hpp
- src/aliceVision/mvsData/imageIO.cpp
- src/aliceVision/mvsData/imageIO.hpp
- src/software/convert/CMakeLists.txt
- src/software/convert/main_convertMesh.cpp
- src/software/pipeline/main_meshFiltering.cpp
- src/software/pipeline/main_meshMasking.cpp
- src/software/pipeline/main_meshing.cpp
- src/software/pipeline/main_texturing.cpp
Generate normal maps and height maps from a high poly model in order to retrieve details on a decimated mesh.
This PR is linked to the following in the meshroom repository : https://github.com/alicevision/meshroom/pull/1508
Plug the **high poly** mesh output from the Meshing  into the Texturing **Ref mesh input**. 
Then plug the **low poly** model to export into the Texturing **mesh input**.
- It is possible to skip a texture generation (Diffuse, NormalMap, HeightMap) by choosing the empty option for the texture file type.
- Heightmaps can only be exported in .exr format.
- In order to have correct results, you should not use a "simple" Decimate node with a vertices count target. Instead, use as many combinations of MeshFiltering following by Decimate node as needed, then use the output …
> Generate NormalMaps and HeightMaps

- src/aliceVision/multiview/resection/CMakeLists.txt
- src/aliceVision/multiview/resection/EPnPSolver.hpp
- src/aliceVision/multiview/resection/Resection6PSolver.cpp
- src/aliceVision/multiview/resection/Resection6PSolver_test.cpp
- src/aliceVision/robustEstimation/LORansac.hpp
- src/aliceVision/sfm/pipeline/localization/SfMLocalizationSingle3DTrackObservationDatabase.hpp
- src/aliceVision/sfm/pipeline/localization/SfMLocalizer.cpp
- src/aliceVision/sfm/pipeline/localization/SfMLocalizer.hpp
Make some modifications such that loRansac work for pose from points.
> [sfm] loRansac debug for PnP

- src/aliceVision/sensorDB/cameraSensors.db
Added Realme 7 Pro to the database. The sensor is a Sony IMX 682, and although hard to find the sensor size I found it on one website as 7.4, and checked it lines up with the calculated size from it's resolution etc.
> Added Realme 7 Pro to sensor database

- src/aliceVision/image/io.cpp
- src/aliceVision/keyframe/KeyframeSelector.cpp
- src/aliceVision/mvsData/imageIO.cpp
- src/software/pipeline/main_panoramaWarping.cpp
CompressionQuality is deprecated in oiio.
Use "zips" compression instead of "piz" as loading exr in piz create issues in Nuke for large images.
> [image] io: use zips compression for exr

- src/aliceVision/sensorDB/cameraSensors.db
Adding an entry for the Canon EOS R6 to the camera sensor database, based on the sensor size data from the Canon product "Advanced User Guide" manual, and from digicamdb.com.
> Add entry to cameraSensors.db for Canon EOS R6

- src/aliceVision/sensorDB/cameraSensors.db
I've tried it by myself and it seems to work out fine.
Source:
https://www.parrot.com/us/drones/anafi/technical-specifications --> Sensor: 1/2.4’’ CMOS
https://www.digicamdb.com/sensor-sizes/ -->1/2.4" (~ **5.90** x 4.43 mm)
> Add Parrot Anafi to sensor database

- src/aliceVision/sensorDB/cameraSensors.db
Adds the canon eos m50 Mark II to the sensor database. It has the same sensor as the previous version.
> Add Canon Eos M50 Mark II to sensor database

- INSTALL.md
`ALICEVISION_BUILD_SHARED` is not used anymore, update the INSTALL.md
> [doc] now aligned with cmake BUILD_SHARED_LIBS

- src/aliceVision/depthMap/Sgm.cpp
Fixes the particular case of 2 cameras in the depth map estimation.
> [depthMap] Sgm: Fix no result with a single Tc

- src/software/pipeline/main_incrementalSfM.cpp
Add `computeStructureColor` option to `incrementalSfM` software to enable/disable color computation of each 3D point.
> [software] incrementalSfM: Add option computeStructureColor

- src/aliceVision/hdr/DebevecCalibrate.cpp
- src/aliceVision/hdr/DebevecCalibrate.hpp
- src/aliceVision/hdr/GrossbergCalibrate.cpp
- src/aliceVision/hdr/GrossbergCalibrate.hpp
- src/aliceVision/hdr/LaguerreBACalibration.cpp
- src/aliceVision/hdr/LaguerreBACalibration.hpp
- src/aliceVision/hdr/brackets.cpp
- src/aliceVision/hdr/hdrMerge.cpp
- src/aliceVision/hdr/hdrMerge.hpp
- src/aliceVision/hdr/sampling.cpp
- src/aliceVision/hdr/sampling.hpp
- src/aliceVision/sfmData/SfMData.hpp
- src/aliceVision/sfmData/View.cpp
- src/aliceVision/sfmData/View.hpp
- src/samples/texturing/main_evcorrection.cpp
- src/software/pipeline/main_LdrToHdrCalibration.cpp
- src/software/pipeline/main_LdrToHdrMerge.cpp
- src/software/pipeline/main_LdrToHdrSampling.cpp
- src/software/pipeline/main_prepareDenseScene.cpp
- src/software/utils/main_imageProcessing.cpp
- use double instead of float
- check if exposures are comparable: hasComparableExposures
> [hdr] new ExposureSetting class

- docker/Dockerfile_ubuntu_deps
Add ca-certificates update to Ubuntu docker build - this is needed for the Kitware CMake repository, as existing certificates in the chain from the base image have expired as of the time of this commit. Installing fresh root certificates should prevent certificate chain-based issues from happening in the future.
- Building the docker image for Focal, I encountered an issue in the certificate chain for the kitware repository (for CMake), preventing the build from progressin nay further
- The issue was simply a stale root certificate, and was resolved by updating the `ca-certificates` package
* As an aside, I use snaps myself for getting a recent build of CMake, this may be easier, although if it ain't broke, don't fix it ;)
- Update the certificates before adding the kitware PPA.
> Add ca-certificates update to Ubuntu docker build.

- src/aliceVision/depthMap/depthMap.cpp
- src/aliceVision/fuseCut/Fuser.cpp
- src/aliceVision/fuseCut/LargeScale.cpp
- src/aliceVision/fuseCut/ReconstructionPlan.cpp
- src/aliceVision/fuseCut/VoxelsGrid.cpp
- src/aliceVision/mvsUtils/MultiViewParams.cpp
- src/aliceVision/mvsUtils/fileIO.cpp
- src/aliceVision/mvsUtils/fileIO.hpp
This PR removes several trivial wrappers of boost::filesystem functionality. Using boost::filesystem directly makes code easier to read and maintain, as there's less things to know about.
> [mvsUtils] Remove trivial boost::filesystem wrappers

- src/aliceVision/fuseCut/CMakeLists.txt
- src/aliceVision/fuseCut/LargeScale.cpp
- src/aliceVision/fuseCut/LargeScale_test.cpp
- src/aliceVision/mvsData/Point3d.hpp
- src/aliceVision/mvsData/Voxel.hpp
- src/aliceVision/mvsUtils/MultiViewParams.cpp
- src/aliceVision/mvsUtils/fileIO.cpp
- src/aliceVision/mvsUtils/fileIO.hpp
This PR removes several uses of C fscanf functionality. Using it directly is unsafe because numeric overflow yields undefined behavior which may crash the program in the worst case. Using C++ equivalents is less problematic, because numeric overflow is well defined there.
A test for changed serialization implementations has been added where possible. A couple of small fixes needed for tests are also included into the PR.
> Remove uses of fscanf

- src/aliceVision/feature/ImageDescriber.cpp
- src/aliceVision/image/io.cpp
- src/aliceVision/mvsData/imageIO.cpp
- src/aliceVision/sfmDataIO/sfmDataIO.cpp
This is trivial PR to fix a particular spelling error that happened in several places.
> Fix typo: temporay -> temporary

- src/aliceVision/mvsData/imageAlgo.cpp
- src/aliceVision/panorama/gaussian.cpp
- src/software/utils/main_lightingEstimation.cpp
The overload of oiio::ImageBufAlgo::make_kernel() that returns the ImageBuf instance via a reference has been deprecated since oiio 1.9. AliceVision requires OpenImageIO >= 2.1.0 so we can switch to the replacement API now.
> Switch to non-deprecated overload of oiio::ImageBufAlgo::make_kernel()

- src/aliceVision/multiview/resection/resectionLORansac_test.cpp
While this memory leak does not matter in practice as it's in tests, it makes ASAN LeakSanitizer happy.
> [multiview] Fix memory leak in resection test

- src/aliceVision/camera/distortion_test.cpp
- src/aliceVision/camera/equidistant_test.cpp
- src/aliceVision/camera/pinhole3DE_test.cpp
- src/aliceVision/camera/pinholeBrown_test.cpp
- src/aliceVision/camera/pinholeFisheye1_test.cpp
- src/aliceVision/camera/pinholeFisheye_test.cpp
- src/aliceVision/camera/pinholeRadial_test.cpp
- src/aliceVision/fuseCut/DelaunayGraphCut_test.cpp
- src/aliceVision/geometry/rigidTransformation3D_test.cpp
- src/aliceVision/lightingEstimation/lightingEstimation_test.cpp
- src/aliceVision/localization/LocalizationResult_test.cpp
- src/aliceVision/localization/rigResection_test.cpp
- src/aliceVision/matchingImageCollection/geometricFilterUtils_test.cpp
- src/aliceVision/multiview/relativePose/essential5PSolver_test.cpp
- src/aliceVision/multiview/resection/resectionKernel_test.cpp
- src/aliceVision/multiview/rotationAveraging/rotationAveraging_test.cpp
- src/aliceVision/multiview/translationAveraging/translationAveraging_test.cpp
- src/aliceVision/multiview/triangulation/triangulation_test.cpp
- src/aliceVision/numeric/numeric.cpp
- src/aliceVision/numeric/numeric.hpp
- src/aliceVision/sfm/pipeline/global/globalSfM_test.cpp
- src/aliceVision/sfmDataIO/alembicIO_test.cpp
- src/aliceVision/voctree/kmeans_test.cpp
- src/aliceVision/voctree/vocabularyTreeBuild_test.cpp
Many tests call Vec*::Random() and similar functions from Eigen, which make the tests not reproducible. This is problematic, because the tests become unstable and even if some of them sometimes fail indicating a problem, it's hard to debug and fix the failure as the exact conditions of the failing test are not known. Initializing random number generators to a static seed fixes the issue.
In order to introduce variation in test execution, `ALICEVISION_TEST_RANDOM_SEED` environment variable can be set to an integer value. This effectively allows to keep the previous behavior, because this value can be set to a different integer on each test execution.
> Improve test reproducibility

- src/aliceVision/image/io.cpp
- src/aliceVision/image/io.hpp
- src/aliceVision/localization/VoctreeLocalizer.cpp
- src/aliceVision/matching/kvld/kvld_draw.h
- src/aliceVision/utils/convert.hpp
- src/aliceVision/voctree/Database.cpp
- src/aliceVision/voctree/Database.hpp
- src/aliceVision/voctree/VocabularyTree.cpp
- src/aliceVision/voctree/VocabularyTree.hpp
- src/samples/robustEssential/main_robustEssential.cpp
- src/samples/robustEssentialBA/main_robustEssentialBA.cpp
- src/software/pipeline/main_cameraLocalization.cpp
- src/software/pipeline/main_meshMasking.cpp
- src/software/pipeline/main_prepareDenseScene.cpp
- src/software/pipeline/main_rigCalibration.cpp
- src/software/pipeline/main_rigLocalization.cpp
- src/software/utils/main_sfmAlignment.cpp
- src/software/utils/main_sfmTransform.cpp
- src/software/utils/main_voctreeQueryUtility.cpp
- src/software/utils/main_voctreeStatistics.cpp
This is related to https://github.com/alicevision/AliceVision/pull/1208. With the ability to compile most of the code that comprises aliceVision pipeline nodes into a single executable, it is now important that there are no duplicate symbols. This PR fixes all of the occurrences of this issue. In many cases this was not just duplicate symbols, but duplicate code as well.
> Fix duplicate symbols across executables

- src/aliceVision/sensorDB/cameraSensors.db
This PR adds the camera sensor (Sony IMX555) for the Samsung Galaxy S21 5G (Samsung SM-G991B).
Width calculation: 4032px * 1.8um/1000 = 7.26mm
Also matches the specs from: https://www.deviceranks.com/en/camera-sensor/718/sony-imx555
> [sensorDB] Add Samsung SM-G991B (Samsung Galaxy S21 5G)

- src/software/pipeline/main_featureMatching.cpp
Option to remove matches without enough motion between the two observations
May be useful to remove matches caused by dirt/dust on sensor
May be useful to remove background features on turning tables
> [Feature Matching] Add an option to remove matches without enough motion

- CMakeLists.txt
- src/CMakeLists.txt
- src/aliceVision/numeric/numeric.hpp
Eigen is most optimal when using SIMD instructions which require overaligned buffers. In C++14 this is a problem because there's no built-in support for correctly aligned allocations, so this Eigen feature is currently disabled in AliceVision. C++17 solves Eigen alignment issues completely because there now exist additional overloads of operator new() which support correct allocation alignment. We can't upgrade to C++17 yet, but certain compilers added support for this feature earlier, such as `-faligned-new` in GCC 7.1.
Given the above it makes sense to add a configuration option to allow enabling alignment support in Eigen in cases when the compiler is good enough (we enable `-faligned-new` automatically). This will improve performance for people who can control the set of supported …
> Add option to compile Eigen with alignment enabled

- src/aliceVision/sensorDB/cameraSensors.db
This pull request adds support for Xiaomi Redmi K30 Pro Zoom Edition in `cameraSensors.db`.
This Android phone matches information from [here](https://www.devicespecifications.com/en/model/39385339).
The main camera sensor is Sony IMX686.
Sensor width = 9248 px * 0.8 µm / 1000 = 7.4 mm
> Add support for Xiaomi Redmi K30 Pro Zoom Edition in cameraSensors.db

- src/aliceVision/hdr/sampling.cpp
- src/aliceVision/mvsUtils/MultiViewParams.hpp
- src/aliceVision/sfmData/colorize.cpp
- src/aliceVision/track/TracksBuilder.cpp
- src/dependencies/flann/src/cpp/flann/algorithms/kdtree_index.h
- src/dependencies/flann/src/cpp/flann/util/lsh_table.h
- src/dependencies/flann/src/cpp/flann/util/random.h
This fixes build on compilers (e.g. Apple Clang) that follow the C++ standard by the letter.
> Remove uses of features removed from C++17 standard

- src/aliceVision/fuseCut/DelaunayGraphCut.cpp
This fixes compile error due to isnormal() being not available in the global namespace. Errors like this most often occur because we accidentally rely on what headers the standard library headers include internally.
> [fuseCut] Pick isnormal() from std namespace

- src/aliceVision/stl/regex.hpp
This fixes "unknown escape sequence: '\/'" warning.
To verify that behavior is identical, run the following:
```
#include <iostream>
int main()
{
std::cout << "\/" << "\n" << "\\\/" << "\n";
std::cout << "/" << "\n" << "\\/" << "\n";
}
```
> [stl] Don't escape a forward slash

- src/nonFree/sift/vl/host.h
Pinning to an old memcpy symver only makes sense on regular Linux, not Android.
> [sift] Remove dependency on glibc memcpy

- INSTALL.md
Just a trivial documentation fix.
> Remove duplicate description of ALICEVISION_USE_OPENMP in INSTALL.md

- src/CMakeLists.txt
- src/aliceVision/camera/distortion_test.cpp
- src/aliceVision/feature/apriltag/ImageDescriber_APRILTAG.cpp
- src/dependencies/flann/src/cpp/flann/mpi/server.h
This PR fixes several compile-time warnings that cause it harder to notice warnings due to genuine problems.
> Fix several compile-time warnings

- src/aliceVision/fuseCut/DelaunayGraphCut.cpp
- src/aliceVision/localization/VoctreeLocalizer.cpp
- src/aliceVision/matchingImageCollection/GeometricFilter.hpp
- src/aliceVision/matchingImageCollection/ImageCollectionMatcher_cascadeHashing.cpp
- src/aliceVision/matchingImageCollection/ImageCollectionMatcher_generic.cpp
- src/aliceVision/sfm/FrustumFilter.cpp
- src/aliceVision/sfm/pipeline/global/GlobalSfMTranslationAveragingSolver.cpp
- src/aliceVision/sfm/pipeline/global/ReconstructionEngine_globalSfM.cpp
- src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
- src/aliceVision/sfm/pipeline/structureFromKnownPoses/StructureEstimationFromKnownPoses.cpp
- src/aliceVision/sfm/sfmTriangulation.cpp
- src/aliceVision/sfmData/colorize.cpp
- src/aliceVision/system/ProgressDisplay.cpp
- src/aliceVision/system/ProgressDisplay.hpp
- src/software/pipeline/main_prepareDenseScene.cpp
The class is very often used in multithreaded contexts, so it makes sense to make it thread safe to avoid repeated locking code.
> Make DisplayProgress class thread safe

- .github/workflows/continuous-integration.yml
This PR just checks whether https://github.com/alicevision/vcpkg/pull/5 passes CI on Windows.
> Update vcpkg dependency for Windows

- src/aliceVision/sfmDataIO/CMakeLists.txt
- src/aliceVision/sfmDataIO/colmap.cpp
- src/aliceVision/sfmDataIO/colmap.hpp
- src/aliceVision/sfmDataIO/colmap_test.cpp
- src/software/export/CMakeLists.txt
- src/software/export/main_exportColmap.cpp
Add the exporter to Colmap to convert an AV SfMData into Colmap's format with the relevant folder structure and the txt files for the scene representation.
* helper functions to extract and convert the scene
* helper functions to test the compatibility of intrinsics
* unit tests
* software to perform the conversion
* Since not all the intrinsic types are compatible between the two libraries, the choice has been made to export only those that are compatible and remove the others from the scene.
* An option is added to copy or not the source images into the Colmap destination folder. This enables the user to skip the copy if all the (many) images are in the same folder: since the first step of Colmap's MVS processing is to remove the optical distortion, that command can be run directly on …
> [software] Add colmap exporter

- src/aliceVision/fuseCut/Fuser.cpp
- src/aliceVision/fuseCut/Fuser.hpp
- src/aliceVision/fuseCut/LargeScale.cpp
- src/aliceVision/fuseCut/LargeScale.hpp
- src/aliceVision/fuseCut/OctreeTracks.cpp
- src/aliceVision/fuseCut/OctreeTracks.hpp
- src/aliceVision/fuseCut/ReconstructionPlan.cpp
- src/aliceVision/fuseCut/ReconstructionPlan.hpp
- src/aliceVision/fuseCut/VoxelsGrid.cpp
- src/aliceVision/fuseCut/VoxelsGrid.hpp
- src/aliceVision/mvsData/StaticVector.cpp
- src/aliceVision/mvsData/StaticVector.hpp
- src/aliceVision/mvsData/structures.hpp
- src/aliceVision/mvsUtils/common.hpp
- src/software/convert/main_importKnownPoses.cpp
- src/software/utils/precisionEvaluationToGt.hpp
This is a simple cleanup PR that removes accidental copies of strings where needed. The performance impact is trivial, but it's still worth to consistently use pass-by-reference lest some function does end up in a critical path.
> Avoid unnecessary string copies

- src/aliceVision/sensorDB/cameraSensors.db
**EN**
Updated cameraSensors.db. I found Actual Metadata of the Maker of K-S2 was RICOH IMAGING COMPANY, LTD. So I updated the corresponding line.
Maker value of newer Models of PENTAX must be same as K-S2, but I can't verify because I don't have them.
Also, Once maker of PENTAX cameras was HOYA corporation(since 2008) and later PENTAX RICOH IMAGING COMPANY, LTD.(since 2011) so I suppose models made in that period may have other metadata value of maker but I'm not sure.
Please review the change and tell me whether you think I should update information of other cameras.
**JA(for reader side machine translation)**
cameraSensors.dbを更新しました。K-S2のメーカーが実際にはRICOH IMAGING COMPANY, LTD.だったので、該当行を更新しました。
より新しいモデルのカメラのメーカー情報も同様にRICOH IMAGING COMPANY, LTD.になっていると思われすが、私はそのようなカメラを持っていないので確かめることができません。 …
> [sensorDB] Update Maker of K-S2 and other DSLRs of Ricoh Imaging

- src/aliceVision/sensorDB/cameraSensors.db
added Galaxy S8 Model SM-G950W with sensor width of 5.66
> [sensorDB] Create camera sensor for Galaxy S8 (Model SM-G950W)

- src/aliceVision/sfmDataIO/CMakeLists.txt
- src/aliceVision/sfmDataIO/colmap.cpp
In the code of `compatibleIntrinsics()`, in order to check if an element belongs to the vector, `find()` was used and compared to the `.end()` of a different vector. (self-facepalm).
This made the unit test fail (only) on windows. Why that was not failing on Linux, it's a big mystery.
Incidentally it fixes the name of the unit test for middlebury, which was missing the proper module prefix
> [bugfix] fix getColmapCompatibleViews 

- src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
This PR includes a relatively simple and small refactor.
The current code recomputes the same source data for both 2 and N observation cases. Due to the code being structured differently it's hard to see that in both cases a lot of the same operations are being performed. By extracting the code into separate function we make this fact explicit.
> [sfm] Reduce code duplication in sequantial sfm triangulation

- src/aliceVision/image/io.cpp
Old overload has been deprecated since oiio 1.9.4. The minimum OpenImageIO version is 2.1.0 so we can replace the old overload unconditionally.
> [image] Fix deprecated use of oiio computePixelStats()

- INSTALL.md
- src/aliceVision/system/ProgressDisplay.cpp
- src/aliceVision/system/ProgressDisplay.hpp
The new boost::timer::progress_display API has been available since Boost 1.72 and the old API was deprecated at the same time. This PR also bumps boost requirement to 1.72.
> [system] Fix deprecated uses of boost::progress_display

- INSTALL.md
- src/aliceVision/alicevision_omp.hpp
- src/aliceVision/fuseCut/DelaunayGraphCut.cpp
- src/aliceVision/mesh/Mesh.cpp
- src/software/pipeline/main_cameraInit.cpp
OMP_ATOMIC_UPDATE and OMP_ATOMIC_WRITE are currently completely broken.
Currently OMP_ATOMIC_UPDATE and OMP_ATOMIC_WRITE are defined as follows:
> #define OMP_ATOMIC_UPDATE _Pragma("omp atomic update")
> #define OMP_ATOMIC_WRITE  _Pragma("omp atomic write")
These macros are used as follows:
> #pragma OMP_ATOMIC_UPDATE
> #pragma OMP_ATOMIC_WRITE
Which results in the following code after preprocessor expansion:
> #pragma _Pragma("omp atomic update")
> #pragma _Pragma("omp atomic write")
This is invalid pragma which is ignored by the compiler. The correct usage of _Pragma is without #pragma as follows:
> _Pragma("omp atomic update")
> _Pragma("omp atomic write")
Fixing this issue reveals another problem that "omp atomic" is very restrictive in what expressions it accepts. In many cases the …
> Fix broken openmp atomic usage

- src/aliceVision/fuseCut/DelaunayGraphCut.cpp
- src/aliceVision/fuseCut/OctreeTracks.cpp
- src/aliceVision/mesh/Mesh.cpp
- src/aliceVision/mesh/Texturing.cpp
- src/aliceVision/mvsUtils/MultiViewParams.cpp
- src/aliceVision/mvsUtils/common.cpp
These functions have overloads accepting std::initializer_list argument which does not introduce performance overheads.
> (trivial) Avoid repeated calls to std::min() or std::max()

- src/aliceVision/image/io.cpp
- src/aliceVision/mvsData/imageIO.cpp
- src/software/utils/main_imageProcessing.cpp
Minimum OpenImageIO version is 2.1.0 which means macros checking for older versions are no longer needed.
> (trivial) Drop code catering to old OpenImageIO versions

- INSTALL.md
- src/software/convert/main_convertFloatDescriptorToUchar.cpp
- src/software/pipeline/main_distortionCalibration.cpp
This PR introduces usage of `boost::filesystem::copy_options` instead of deprecated equivalent.
The new API has been introduced in Boost 1.74 and follows C++17 more closely.
Boost dependency has been bumped to 1.74. This is harmless because users will either use system Boost, which is 1.74 on both Debian stable (bullseye) and Ubuntu 22.04 LTS, or compile from source on older systems or RHEL which already has older Boost anyway. Therefore bumping the requirement is harmless.
I don't think we should upgrade to even newer boost because this would force even more libraries to be recompiled from source and included into AliceVision install prefix when developing even on relatively new systems.
> Don't use deprecated filesystem copy options

- src/aliceVision/fuseCut/DelaunayGraphCut.cpp
- src/aliceVision/numeric/numeric.hpp
- src/aliceVision/numeric/numeric_test.cpp
The intention in cases like `std::ceil(a / b)` (where `a` and `b` are integers) likely was to get floating-point division result and round it upwards. However, the division was performed with integer arguments, fractional part was lost and thus `std::ceil` did nothing. This PR introduces a separate function to perform such integer division and fixes the buggy cases.
If the original intention was wrong, this PR will break behavior. According to my limited understanding of the code the original intention was correct.
A subsequent PR will change all similar cases where we currently do `int(std::ceil(double(a) / double(b)))` to use `divideRoundUp()`.
> Fix wrong integer division where rounding up was intended

- src/aliceVision/fuseCut/DelaunayGraphCut.cpp
- src/aliceVision/matching/matchesFiltering.cpp
- src/aliceVision/mesh/Texturing.cpp
- src/aliceVision/panorama/boundingBox.hpp
- src/aliceVision/panorama/panoramaMap.cpp
- src/software/pipeline/main_panoramaCompositing.cpp
- src/software/pipeline/main_panoramaSeams.cpp
This PR cleans up the cases where integer division with routing up was intended by reusing `divideRoundUp()`. Differently from https://github.com/alicevision/AliceVision/pull/1254, this PR does not improve any problematic behavior.
> Consistently use divideRoundUp() for integer division with rounding up

- src/aliceVision/calibration/distortionEstimation.cpp
- src/aliceVision/sfm/BundleAdjustmentCeres.cpp
- src/aliceVision/sfm/BundleAdjustmentPanoramaCeres.cpp
- src/aliceVision/sfm/BundleAdjustmentSymbolicCeres.cpp
- src/aliceVision/sfm/liealgebra.hpp
- src/aliceVision/utils/CeresUtils.hpp
ceres-solver deprecated `LocalParameterization` in favor of `Manifold` in v2.1. v2.2 will not contain `LocalParameterization` anymore. This PR bumps ceres-solver dependency to at least v2.1 which has been released on 2022-03-28.
This PR also fixes an ODR violation that was caused by two local classes named `alicevision::sfm::IntrinsicsManifold` present in two different translation units.
> Fix ceres-solver deprecations

- src/aliceVision/sensorDB/cameraSensors.db
Add sensor database entries for the OnePlus 8 Pro model numbers.  These are regional variations of the device, which all have the same camera.
> Add OnePlus 8 Pro to the sensor database

- .github/workflows/continuous-integration.yml
Hopefully this fixes the CI on Windows. Current failures fail due to missing include file from boost which exists in the release that we use, so I assume the file was not installed for some reason, the CI did not notice this failure and stored broken artifacts into cache.
> [github] Append to vcpkg cache key to expire broken CI cache

- src/aliceVision/image/io.cpp
- src/aliceVision/image/io.hpp
- src/software/pipeline/main_cameraInit.cpp
This allows to override the returned value if needed, e.g. in tests. Idea comes from this comment: https://github.com/alicevision/AliceVision/pull/1170#discussion_r990088525
> [image] Introduce a function to retrieve ALICEVISION_ROOT

- src/aliceVision/sfmDataIO/colmap.cpp
Missing include in colmap.cpp
Does not build on some computers under centOS
> [sfmDataIO] Missing fstream include

- src/aliceVision/mvsUtils/common.cpp
- src/aliceVision/sfm/pipeline/global/ReconstructionEngine_globalSfM.cpp
- src/aliceVision/sfm/pipeline/panorama/ReconstructionEngine_panorama.cpp
In a couple of places `std::pow` was used where `std::sqrt` would suffice. In another place `std::pow` and `std::sqrt` pair could be replaced with `std::abs`.
> (trivial) Cleanup std::pow usages

- src/aliceVision/voctree/SimpleKmeans.hpp
This PR fixes 3 performance problems in voctree which cause inefficiency for relatively small problems:
- all center updates depend on a single lock during clustering
- thread pool is created per-iteration during clustering
- thread pool is created per-iteration during k-means initialization
This PR disables parallelism in case problem size is small and introduces a lock for each cluster center to help when this is not the case. Additionally, k-means initialization now runs in parallel for trials which reduces the thread fanout when calculating new distance sum.
I haven't tested this with large problems, but at least vocabularyTreeBuild test became faster by up to 40 times on a machine with AMD 2990WX (~4s -> 0.1s). The runtime of another relevant test `voctree_kmeans` has been improved …
> Optimize voctree build by up to 40 times for certain problems

- src/aliceVision/matchingImageCollection/CMakeLists.txt
- src/aliceVision/matchingImageCollection/GeometricFilter.cpp
- src/aliceVision/matchingImageCollection/GeometricFilter.hpp
- src/software/pipeline/main_featureMatching.cpp
This extract another function that I've found useful into a module from where it can be reused.
> (trivial) Extract removePoorlyOverlappingImagePairs()

- CMakeLists.txt
Zlib 1.2.13 has been released on October 13th 2022 and the previous version is not available at that link anymore.
So bump to the latest version with the proper hash, since it's a patch version there should be no conflicts.
> [cmake][dep] bump zlib to 1.2.13

- CMakeLists.txt
For some reasons it is not automatically built anymore in 1.76, maybe it was built because it was a dependency of another module. But it is needed.
> [cmake][dep] missing iostreams in boost 1.76

- src/aliceVision/calibration/distortionEstimation.cpp
- src/aliceVision/camera/IntrinsicBase.hpp
- src/aliceVision/camera/IntrinsicsScaleOffsetDisto.hpp
- src/aliceVision/sfm/BundleAdjustmentPanoramaCeres.cpp
I've accidentally noticed that distortion calibration takes a lot of time in `std::vector` operations. Closer inspection revealed that we're copying data unnecessarily when setting distortion parameters. This PR optimizes this operation by giving the caller an option to supply a callback with which appropriate number of parameters will be initialized with all the usual error checking.
On a machine with AMD 2990WX (with turbo boost disabled) this PR improves the run-time of `test_calibration_distortion` test from ~3.9s to ~3.1s.
> Optimize distortion calibration by 1.25x for certain problems

- src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
- src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.hpp
In the incremental SFM, the reconstruction select iteratively some candidates for resection. It may happens that this selection is not good and the resection fail. In this case, the frame is definitely discarded. This PR gives them other chances to shine ! 
- If a resection fail, the frame id is **not** removed from the set of available frames.
- To make sure we don't retry at each iteration those frames, we estimate at each iteration which frames are affected by the changes on the reconstruction in the current iteration. For all frames which have been newly inserted into the reconstruction, trigger the connected frames (through tracks) for the next iteration.
> [sfm] make sure we give other chances to candidates

- src/aliceVision/sensorDB/cameraSensors.db
- src/aliceVision/sensorDB/sensorDatabaseSort.py
In this PR we update the camera sensor database with the latest sensor data from dxomark, dpreview, imagingresource and digicamdb.
> [sensorDB] update sensor data from websites

- src/software/utils/main_sfmColorHarmonize.cpp
- src/software/utils/sfmColorHarmonize/colorHarmonizeEngineGlobal.cpp
- src/software/utils/sfmColorHarmonize/colorHarmonizeEngineGlobal.hpp
In this PR we update the `enum` system used for the `selectionMethod` argument of `sfmColorHarmonize` to use an `enum class` that works the same way as other `aliceVision` executables instead.
> [sfmColorHarmonize] update selection method enum and command-line argument

- CMakeLists.txt
Follow up of PR #1241 to update the dependencies built in the CMake script to TBB oneAPI.
TBB is used in CCTAG and to compile under Silicon a more recent version is needed.
This PR is related to https://github.com/alicevision/CCTag/pull/200 that introduces the fixes to compile CCTag with this new version of TBB.
> [cmake][dep] update TBB to oneAPI version

- src/aliceVision/depthMap/computeOnMultiGPUs.cpp
- src/aliceVision/feature/FeatureExtractor.cpp
- src/aliceVision/feature/FeatureExtractor.hpp
- src/aliceVision/system/CMakeLists.txt
- src/aliceVision/system/cmdline.cpp
- src/aliceVision/system/cmdline.hpp
- src/aliceVision/system/hardwareContext.cpp
- src/aliceVision/system/hardwareContext.hpp
- src/software/pipeline/main_LdrToHdrCalibration.cpp
- src/software/pipeline/main_LdrToHdrMerge.cpp
- src/software/pipeline/main_LdrToHdrSampling.cpp
- src/software/pipeline/main_featureExtraction.cpp
- src/software/pipeline/main_incrementalSfM.cpp
- src/software/pipeline/main_panoramaCompositing.cpp
- src/software/pipeline/main_panoramaSeams.cpp
- src/software/pipeline/main_panoramaWarping.cpp
- src/software/utils/CMakeLists.txt
```c
boost::program_options::options_description hardwareParams("Hardware parameters");
hardwareParams.add_options()
("maxMemoryAvailable", boost::program_options::value<size_t>(&_maxMemoryAvailable)->default_value(_maxMemoryAvailable), "User specified available RAM")
("maxCoresAvailable", boost::program_options::value<unsigned int>(&_maxCoresAvailable)->default_value(_maxCoresAvailable), "User specified available number of cores");
> Allow parameters to limit the number of Cores used and Memory available information

- src/aliceVision/system/hardwareContext.cpp
Bad types in comparison in HardwareContext::displayHardware() causing memory user parameter to never be displayed
> [system] minor fix on HardwareContext log

- .github/workflows/continuous-integration.yml
- src/aliceVision/hdr/hdrTestCommon.hpp
- src/aliceVision/hdr/sampling.cpp
- src/aliceVision/hdr/sampling.hpp
- src/aliceVision/image/CMakeLists.txt
- src/aliceVision/image/all.hpp
- src/aliceVision/image/dcp.cpp
- src/aliceVision/image/dcp.hpp
- src/aliceVision/image/io.cpp
- src/aliceVision/image/io.hpp
- src/aliceVision/sfmData/View.hpp
- src/software/pipeline/main_LdrToHdrMerge.cpp
- src/software/pipeline/main_LdrToHdrSampling.cpp
- src/software/pipeline/main_cameraInit.cpp
- src/software/pipeline/main_panoramaPrepareImages.cpp
- src/software/utils/main_colorCheckerCorrection.cpp
- src/software/utils/main_colorCheckerDetection.cpp
- src/software/utils/main_imageProcessing.cpp
Add dcp color profile loading and applying capabilities when raw images must be read.
In cameraInit node, using the maker and model metadata, if a color profile database is provided, the complete filepath of the appropriate dcp file is added in the image metadata. Then, every time the image has to be read, the color profile can be applied. Application options are available. As a consequence if a node wants to get the original raw images, this is still possible by deactivating the color profile application.
A new parameter in cameraInit node allows to select the error level (warning or error) when a database is provided but no adapted color profile is found for a raw input image.
> Color management for RAW images

- src/CMakeLists.txt
- src/aliceVision/image/convertionOpenCV.hpp
- src/software/utils/main_imageProcessing.cpp
This PR adds a new denoising method (Non-Local Means from OpenCV) in the ImageProcessing node.
NL Means support in Meshroom is added in alicevision/Meshroom#1719.
- Implementation inspired by bilateralFilter
- NLMeans is a 8-bit denoiser so conversion from float to unsigned char is managed
> Add NLMeans denoiser in ImageProcessing

- src/aliceVision/geometry/Pose3.hpp
When building QtAliceVision, M_PI generates C2065 errors (undeclared identifiers) on Windows, even with the correct includes. Replacing it with Boost's pi fixes this error.
> [build] Use Boost's pi constant instead of M_PI in Geometry

- src/aliceVision/image/io.cpp
If the version of OIIO is lower than 2.4.5.0, the cam_mul metadata is missing and raw decoding using a dcp profile is not fully possible. Avoid possible crash by setting a default value for cam_mul and add a warning.
> read image with missing cam_mul metadata

- INSTALL.md
[doc] INSTALL: replace geogram broken link
fix
Change geogram install broken link from https://gforge.inria.fr/frs/?group_id=5833 to https://github.com/BrunoLevy/geogram
> [doc] INSTALL: replace geogram broken link

- src/aliceVision/image/dcp.cpp
- src/software/pipeline/main_LdrToHdrMerge.cpp
- src/software/pipeline/main_LdrToHdrSampling.cpp
- src/software/pipeline/main_cameraInit.cpp
Throw an error instead of a warning when trying to load a non existing DCP profile.
cameraInit: rawColorInterpretation automatically switch to librawWhiteBalancing mode and throw a warning when a DCP profile is required but no error is requested if it is missing and no database or an erroneous one is given as parameter or if the expected profile does not exist in the database.
Add working color space as a parameter in sampling and merging HDR exec.
> DCP error management

- src/aliceVision/sensorDB/cameraSensors.db
https://www.dji.com/en/mavic-3-enterprise/specs
"DJI Mavic 3T : CMOS 1/2" => 6.4 mm
> [sensorDB] Add DJI Mavic 3T

- src/aliceVision/feature/imageDescriberCommon.cpp
- src/aliceVision/image/convertionOpenCV.hpp
- src/aliceVision/sfm/pipeline/ReconstructionEngine.cpp
- src/aliceVision/sfmDataIO/sfmDataIO_test.cpp
- src/software/pipeline/main_featureExtraction.cpp
`config.hpp` should be always included ("include what you use") when using Alicevision's macros defined in there.
> add missing config.hpp include

- src/CMakeLists.txt
When checking for ocv contrib module, `ALICEVISION_HAVE_OPENCV_CONTRIB` was never initialized to 0.
This should solve #1338 if the user do not ask explicitly to build with OpenCV.
If it is not the case, then `ALICEVISION_HAVE_OPENCV_CONTRIB` is never set while later on in the software module is checked to build or not some of the programs
> [cmake] fix for `ALICEVISION_HAVE_OPENCV_CONTRIB`

- src/aliceVision/hdr/brackets.cpp
- src/aliceVision/hdr/brackets.hpp
- src/aliceVision/hdr/hdrTestCommon.hpp
- src/aliceVision/hdr/sampling.cpp
- src/aliceVision/hdr/sampling.hpp
- src/software/pipeline/main_LdrToHdrCalibration.cpp
- src/software/pipeline/main_LdrToHdrMerge.cpp
- src/software/pipeline/main_LdrToHdrSampling.cpp
Use samples in calibration node to determine the reference exposure for each grouped views. Write results in a text file in the same directory as the response file. In the merge node, read the file containing the reference indexes and use them to compute the HDR image.
In the calibration node, for all exposure levels of each group of views, the mean, max an min values of luminance are computed from all the mean rgb info contained in the loaded image samples. For each group of views, the index of the reference image is deduced from those stats. The average of those computed indexes is written in a text file located in the same directory as the response file already delivered by the node.
In the merging node, the file is read and the index is used to build the HDR image. A parameter is …
> [hdr] Compute the center exposure of the hdr automatically

- src/aliceVision/hdr/brackets.cpp
- src/software/pipeline/main_LdrToHdrCalibration.cpp
HDR Calibration bug fix at generation of file containing the luminance statistics.
Guarantee that every views have an associated luminance info.
In HDR merging node, throw an "invalid file" error when reading the file if it does not contain the expected number of lines.
> HDR luminance statistics bugfix

- src/aliceVision/sfm/utils/alignment.cpp
- src/aliceVision/sfm/utils/alignment.hpp
- src/software/utils/main_sfmTransform.cpp
User can align the panorama horizontally with a target view. Need to select auto_from_cameras_x_axis in sfmTransform.
> Panorama alignment with a reference camera

- INSTALL.md
> [doc] update INSTALL as osi is not internal anymore

- src/software/pipeline/main_panoramaCompositing.cpp
- src/software/pipeline/main_panoramaMerging.cpp
Actually, compositing is done using some kind of tiling to handle large panorama. In case of small panoramas, this tiling has useless overhead. This PR propose to control if tiling is used.
> [Panorama] New option to disable compositing tiling

- src/aliceVision/image/dcp.cpp
- src/aliceVision/image/dcp.hpp
- src/aliceVision/image/io.cpp
- src/aliceVision/image/io.hpp
- src/software/pipeline/main_LdrToHdrMerge.cpp
- src/software/pipeline/main_panoramaPostProcessing.cpp
- src/software/utils/main_imageProcessing.cpp
Expose some parameters dedicated to raw decoding and DCP color profile application.
libraw parameters: highlight Mode, demosaicking algo
White Balancing: Before (libraw) or after (AV) demosaicking
DCP parameter: apply Color Matrix only
Enable reading of images containing raw data in a non raw format (exr)
Add option to select the output color space of a RS panorama in panorama post processing node.
> RAW advanced processing

- src/software/pipeline/main_panoramaCompositing.cpp
[panorama] force pyramid levels count in compositing
> [panorama] force pyramid levels count in compositing

- src/software/utils/main_split360Images.cpp
The `dualfisheye` split mode of the `aliceVision_split360Images` software is currently broken, as it only saves on disk two fully black images.
This problem seems to be related to the use of oiio image buffers for copying data.
In this PR, we replace the previous approach with a simpler one: since images are eigen matrices, we copy the blocks we need from the source image and save them, hence there is no need to use oiio at any point.
Some extra modifications have been made to the `aliceVision_split360Images` software:
- the extracted images are saved on disk using a rig structure
- the "demo" mode has been renamed to "preview" mode
- the user can now specify the output image extension
These changes of the command-line and output folder structure have 2 side-effects:
- software version …
> [software] fix split dual fisheye

- src/software/utils/main_imageProcessing.cpp
In imageProcessing, check input image format before setting some reading options and searching for a dcp profile if required. A non raw image format can be read even if a dcp profile does not exist for the camera used to capture the input image. This behavior matches the cameraInit one.
> Fix reading non raw image format in imageProcessing.

- INSTALL.md
This PR updates the list of packages to install with vcpkg in INSTALL.md and adds a recommended version for OpenImageIO.
> [doc] INSTALL: Update the list of vcpkg packages to install

- RELEASING.md
> [doc] add RELEASING.md

- src/aliceVision/image/io.cpp
- src/software/utils/main_imageProcessing.cpp
Set ".exr" as default output extension if input image is in a raw file format in imageProcessing.
Replace some INFOs with TRACEs in read image.
> Fix crash when output extension is missing in image processing

- src/aliceVision/dataio/FeedProvider.cpp
When building Alicevision without relying on opencv, you will encounter compilation errors. I checked the problem and found that the static function isSupported() of VideoFeed was called, but VideoFeed did not compile because it did not depend on the opencv library.
I have provided a way to fix this problem, please review it if you have time.@fabiencastan 
- [1 ] Feature one. Fix building without opencv
> Fix building without opencv

- src/software/pipeline/main_panoramaCompositing.cpp
Change the common scale selection for the various chunks.
I replaced min scale with max scale as the common scale for the laplacian compositing.
> [panorama] compositing common scale selection

- BIBLIOGRAPHY.md
- src/CMakeLists.txt
- src/aliceVision/calibration/CMakeLists.txt
- src/aliceVision/calibration/checkerDetector.cpp
- src/aliceVision/calibration/checkerDetector.hpp
- src/aliceVision/calibration/checkerDetector_io.cpp
- src/aliceVision/calibration/checkerDetector_io.hpp
- src/software/pipeline/CMakeLists.txt
- src/software/pipeline/main_checkerboardDetection.cpp
This PR introduces a new checkerboard detection software and improves the previous checkerboard detection algorithm.
The detection code was cherry-picked from this PR: https://github.com/alicevision/AliceVision/pull/1291.
The corresponding Meshroom node has been introduced in this PR: https://github.com/alicevision/Meshroom/pull/1869.
- Robust checkboard detection
- Support for nested calibration grids
- Detected boards visualization on top of input images
- Checkerboard detection software
Tested on: 
- standard datasets with calibration grid directly facing the camera
- calibration grids not directly facing the camera and seen under different tilt conditions
- images taken with an anamorphic lens
- nested calibration grids.
> [calibration] Checkerboard detection

- src/aliceVision/sfm/utils/alignment.cpp
- src/aliceVision/sfm/utils/alignment.hpp
- src/software/utils/main_sfmTransform.cpp
New sfmTransform Node
- Use cameras X axis to estimate the horizontal plane (and the horizon)
- Use GPS measurements (if available) to align the Z axis with the north
- Use GPS measurements (if available) to set the scale (otherwise scaled such that stddev=1)
- Use cameras center mean as frame origin
See https://github.com/alicevision/Meshroom/pull/1954
> [sfmTransform] Creation of auto mode

- RELEASING.md
This PR adds an example of the command to use to generate the release note.
```
./github-generate-release-note.py -o alicevision -r AliceVision -m MAJOR.MINOR.PATCH --highlights major-feature --label-include scope:ci,scope:doc,scope:build sensordb -s updated-asc
```
generates a list of all the closed pull requests for the milestone MAJOR.MINOR.PATCH with:
- a "Main features" section (`highlights`) containing all the PRs tagged with the label `major-feature`;
- an "Other improvements" section that contains all the PRs that are not tagged with the labels used in `label-include`;
- two sections (`label-include`) containing respectively:
- all the PRs tagged with labels `scope:ci`, `scope:doc`, `scope:build`;
- all the PRs tagged with the label `sensordb`.
All the pull requests are sorted …
> [doc] RELEASING: Add example command to generate the release note

- src/aliceVision/dataio/CMakeLists.txt
- src/aliceVision/dataio/FeedProvider.cpp
- src/aliceVision/dataio/FeedProvider.hpp
- src/aliceVision/dataio/IFeed.cpp
- src/aliceVision/dataio/IFeed.hpp
- src/aliceVision/dataio/ImageFeed.cpp
- src/aliceVision/dataio/ImageFeed.hpp
- src/aliceVision/dataio/SfMDataFeed.cpp
- src/aliceVision/dataio/SfMDataFeed.hpp
- src/aliceVision/dataio/VideoFeed.cpp
- src/aliceVision/dataio/VideoFeed.hpp
- src/aliceVision/keyframe/CMakeLists.txt
- src/aliceVision/keyframe/KeyframeSelector.cpp
- src/aliceVision/keyframe/KeyframeSelector.hpp
- src/aliceVision/keyframe/README.md
- src/software/utils/main_keyframeSelection.cpp
This PR builds on top of #1343 and:
1. Adds the support of `SfMData` files as an input;
2. Outputs two `SfMData` files: one that contains the selected keyframes, and one that contains all the frames that failed to be selected as keyframes.
`SfMData` files can now be provided as inputs for both the regular and smart keyframe selection, and the selection methods remain oblivious to the type of input they are given. **Rigs are not supported with `SfMData` files as inputs.**
Once the keyframes have been written, two `SfMData` files are written, respectively with the keyframes' information and the rejected frames' information. Depending on the type of input, the output `SfMData` files are written with the following specifications:
- If the input is an image sequence (or a rig of image …
> Keyframe Selection: Add support for SfMData files as inputs and outputs

- src/software/pipeline/main_panoramaPostProcessing.cpp
PanoramaPostProcessing generates a small resized panorama along the full-res panorama.
Default size is 1000*500 but may be modified through previewSize parameter
https://github.com/alicevision/Meshroom/pull/1944
> [panorama] Generate a preview panorama

- src/aliceVision/sfm/pipeline/pairwiseMatchesIO.hpp
- src/aliceVision/sfm/pipeline/regionsIO.cpp
- src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
- src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.hpp
- src/software/pipeline/main_incrementalSfM.cpp
This PR exposes two previously hard-coded parameters to the Incremental Structure From Motion command line:
- `nbFirstUnstableCameras`, which sets the number of cameras for which the bundle adjustment is performed every time a new camera is added. Past `nbFirstUnstableCameras` cameras, the bundle adjustment is only performed once every N cameras, with N up to `maxImagesPerGroup`;
- `maxImagesPerGroup`, which sets the maximum number of cameras that can be added before the bundle adjustment has to be performed again.  
Additionally, debug logs have been added to monitor the feature and match folders that are provided, and those that are actually loaded. 
Related pull request in Meshroom: https://github.com/alicevision/Meshroom/pull/1980
> SfM: Expose new parameters to the command line

- src/software/pipeline/main_cameraInit.cpp
`rigHasUniqueFrameIds` check should only be used on views that belong to an actual rig.
> [pipeline] cameraInit: fix rigHasUniqueFrameIds

- src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
- src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.hpp
- src/software/pipeline/main_incrementalSfM.cpp
The goal of this PR is to expose an internal variable used in the sequential SfM reconstruction engine called `nbOutliersThreshold`.
This variable is now accessible through the parameters of the reconstruction engine and the incremental SfM command line.
> IncrementalSfM: expose nbOutliersThreshold param

- .clang-format
- CMakeLists.txt
- INSTALL.md
- src/CMakeLists.txt
- src/aliceVision/fuseCut/CMakeLists.txt
- src/aliceVision/fuseCut/Fuser.hpp
- src/aliceVision/hdr/hdrTestCommon.hpp
- src/aliceVision/multiview/relativePose/fundamental10PSolver_test.cpp
- src/aliceVision/track/tracksUtils.hpp
- src/dependencies/flann/src/cpp/flann/util/heap.h
Upgrade to C++ standard from 14 to 17.
Impact:
- CUDA: >= 11.
- GCC: >= 7.0
https://gcc.gnu.org/projects/cxx-status.html#cxx17
- VS: Visual Studio 2017 15.8 (MSVC 19.15) and later supports all C++17 language features.
https://en.cppreference.com/w/cpp/compiler_support/17
> [cmake] Update CXX standard from 14 to 17

- .clang-format
Error with Visual Studio 2022 Community while formatting with clang format
> Fix .clang-format after updating CXX standard

- src/aliceVision/image/io.cpp
Manage openImageIO GammaX.Y color space occuring on some png images by reversing the gamma correction and setting sRGB linear as original color space. The gamma value is obtained by decoding the X.Y substring in the color space name delivered by openImageIO.
Related to: https://github.com/alicevision/AliceVision/issues/1365
Managing GammaX.Y color spaces in this way prevents to update the OCIO configuration file.
> oiio gammaX.Y color spaces management

- src/aliceVision/image/io.cpp
- src/aliceVision/image/io.hpp
- src/software/utils/main_imageProcessing.cpp
Add option for setting maximum width and height in imageProcessing.
Use libRaw settings for automatic and manual exposure adjustment when reading raw images. Add relying options in imageProcessing.
> Exposure and format adjustment

- src/aliceVision/sfm/utils/alignment.cpp
- src/aliceVision/sfm/utils/alignment.hpp
- src/software/utils/main_sfmTransform.cpp
Simple Ground level alignment.
Objective : make sure the lower geometric structure is at Y=0
Assumes the Y axis is the true vertical axis
Remove all points which are not "under" one camera which observes it.
Remove all points which are not observed correctly
Remove statistical noise. Takes the lower point as the ground.
> Ground level alignment based on sfm point cloud

- src/aliceVision/fuseCut/DelaunayGraphCut.cpp
When a surface is close to the specified bounding box, a lot of small holes in the corresponding mesh appear. Additionally, there's a double surface phenomena that is created where an irregular surface appears behind the actual surface in question.
| ![image](https://github.com/alicevision/AliceVision/assets/72821992/c3ae27a8-570b-4e96-8b8c-91c0627e6665)<br>*Without manual bounding box (before fix)* | ![image](https://github.com/alicevision/AliceVision/assets/72821992/5e936a0b-77d1-4ee7-ac58-fd88966de8f5)<br>*With manual bounding box (before fix)* |
|:--:|:--:|
| ![image](https://github.com/alicevision/AliceVision/assets/72821992/7387c4ab-64b5-4e18-b6d5-d97ed7815564)<br>*Without manual bounding box (after fix)* | ![image](https://github.com/alicevision/AliceVision/assets/72821992/e1999bc4- …
> [Meshing] Fix to avoid small holes in the final mesh

- src/aliceVision/sensorDB/cameraSensors.db
The Pixel 7 family uses the same Samsung GN1 sensor as the Pixel 6.
> Add Google Pixel 7/7 Pro main camera to cameraSensors.db

- src/software/utils/CMakeLists.txt
- src/software/utils/main_split360Images.cpp
The goal of this PR is to add support for using SfMData files for the input and output of the `aliceVision_split360Images` software.
Corresponding Meshroom PR: https://github.com/alicevision/Meshroom/pull/1939
The output SfMData file created by `aliceVision_split360Images` has the following characteristics:
- all views belong to the same rig
- this rig's ID is 0
- all views share the same intrinsic
- this intrinsic's ID is 0
- the camera model for the intrinsic is radial3 for equirectangular split and either fisheye4 or equidistant_r3 for dual fisheye (user choice)
- the intrinsic's sensor size is always 36mm x 36mm
- in dual fisheye mode, if no focal metadata is found, an initial guess on the field of view if made with the value 170 degrees.
> [utils] split360Images: support SfMData input and output

- src/aliceVision/image/ImageCache.hpp
The goal of this PR is to refine the image caching system previously introduces by adding new functionnalities and improving code quality.
- new `contains` method for checking if a given image is in the cache (without affecting LRU ordering)
- new `cachedOnly` flag to retrieve an image only if it is in the cache (i.e no image will be loaded from disk)
- new `lazyCleaning` flag to enable/disable lazy cleaning (= cleaning large images in priority instead of respecting LRU ordering)
- bug fix related to the `missingCapacity` computation
> [image] ImageCache improvements

- src/software/utils/main_applyCalibration.cpp
In the special case where the `calibration` input of the `applyCalibration` software is empty, simply pass on the input instead of failing.
This is useful for the new camera tracking pipeline in Meshroom  when users want to disconnect the calibration pipeline (for example if there is no lens grid).
> [software] applyCalibration: simply copy input data when calibrated data filename is empty

- INSTALL.md
Broken link was fixed by https://github.com/alicevision/AliceVision/pull/1327 but then readded by https://github.com/alicevision/AliceVision/pull/1215.
> [doc] INSTALL.md: remove geogram broken link

- src/aliceVision/sfmDataIO/AlembicImporter.cpp
Fix bug with undistortion object dimensions not being initialized, leading to NaN values when calculating undistorted positions of feature points.
> [sfmDataIO] Alembic Import: initialize intrinsics properly

- src/software/pipeline/main_featureExtraction.cpp
- src/software/pipeline/main_prepareDenseScene.cpp
Related Meshroom pull request: https://github.com/alicevision/Meshroom/pull/2039
This PR changes the behaviour of nodes with chunks that check the validity of the ranges they are provided with. Instead of causing an `EXIT_FAILURE` when the starting point of the range exceeds the number of views in the SfMData, we detect whether the size of the range with this starting point is negative (which means that the chunks were created based on erroneous information), and skip the computations before returning `EXIT_SUCCESS`. 
This allows to use chunks after nodes whose announced size does not always correspond to the reality, because their number of outputs cannot be precisely determined before their computation.
This PR affects the `PrepareDenseScene` and `FeatureExtraction` executables.
> [software] Do not fail if range start is larger than the number of views

- src/aliceVision/keyframe/KeyframeSelector.cpp
- src/aliceVision/keyframe/README.md
- src/software/utils/main_keyframeSelection.cpp
Related Meshroom pull request: https://github.com/alicevision/Meshroom/pull/2036
This PR adds a new supported value to the `outputExtension` parameter, `none`, that disables the export of selected keyframes on disk when it is set.
Up until now, the selected keyframes were always written on disk at the same time as the SfMData files, and there was no way to avoid this. By setting `outputExtension` to `none`, only the two SfMData files (one containing the selected keyframes, one containing the frames that were not selected) will be written.
Not writing the selected keyframes on disk results in a slight performance improvement as less I/O operations are performed.
**Note:** `outputExtension` should not be set to `none` when the input is a video: since the frames from the video are not …
> KeyframeSelection: Add new parameter value to disable the export of keyframes

- src/aliceVision/camera/Equidistant.hpp
- src/aliceVision/camera/EquidistantRadial.hpp
- src/aliceVision/camera/IntrinsicBase.hpp
- src/aliceVision/camera/IntrinsicsScaleOffset.hpp
- src/aliceVision/camera/IntrinsicsScaleOffsetDisto.hpp
- src/aliceVision/camera/Pinhole.hpp
- src/software/pipeline/main_panoramaInit.cpp
- PanoramaInit was using a default constructor to create fisheye. This default constructor was not creating the distortion object. Fisheye did not have distortion parameters.
- Make sure the cameras clone function is a deep copy and not a shallow copy (Distortion is now cloned instead of copied)
> Debug in camera object

- src/software/pipeline/main_panoramaCompositing.cpp
TO enhance very large panoramas, i introduced a problem in short focal panoramas.
The memory usage was too large for no reason. This is a temporary fix until we have dynamic chunks
> Panorama was using too much memory for no reason

- src/aliceVision/image/io.cpp
- src/software/pipeline/main_panoramaInit.cpp
Make sure libraw does not reorient our buffer.
A PR is under review at OiiO to give back the flip value even if its application is disabled.
https://github.com/OpenImageIO/oiio/pull/3669
> Disable libraw flip 

- src/aliceVision/feature/FeatureExtractor.cpp
- src/aliceVision/feature/FeatureExtractor.hpp
- src/software/pipeline/main_LdrToHdrMerge.cpp
- src/software/pipeline/main_featureExtraction.cpp
- src/software/pipeline/main_panoramaCompositing.cpp
- src/software/pipeline/main_panoramaWarping.cpp
Enable color space selection at stitching level.
> Stitching color space

- src/aliceVision/mvsUtils/mapIO.cpp
minDepth and maxDepth were not being written for filtered depthmaps (see issue https://github.com/alicevision/AliceVision/issues/1466).
This PR should fix the issue (proposed by @gregoire-dl ).
closes https://github.com/alicevision/AliceVision/issues/1466
> [mvsUtils] fix writing metadata for filtered depthmaps

- docker/Dockerfile_centos_deps
- docker/Dockerfile_ubuntu_deps
- docker/fetch.sh
This PR updates the docker files to download the sphere detection model, which is used in the stereo photometry pipeline, and set its corresponding environment variable. (following #999)
> [docker] Download, copy and export the sphere detection model

- src/aliceVision/image/io.cpp
Activate the libRaw balance_clamping and adjust_maximum_thr options when reading raw images in order to limit highlight color cast.
Set demosaicing option when libRaw is used for color management.
> Set LibRaw options

- src/aliceVision/sfmData/SfMData.cpp
CameraPose lock was not set when loading alembic
SfmData::setPose(const CameraPose & pose) was not copying the lock
> CameraPose lock was not correctly loaded
