alicevision/AliceVision

src/openMVG/dataio/AlembicExporter.cpp
src/openMVG/dataio/AlembicExporter.hpp
src/openMVG/dataio/AlembicImporter.cpp
src/openMVG/exif/exif_IO.hpp
src/openMVG/exif/exif_IO_EasyExif.hpp
src/openMVG/exif/exif_IO_test.cpp
src/openMVG/sfm/sfm_data.hpp
src/openMVG/sfm/sfm_view.hpp
src/openMVG/sfm/sfm_view_metadata.hpp
src/software/SfM/main_SfMInit_ImageListing.cpp
src/third_party/easyexif/CONTRIBUTORS
src/third_party/easyexif/LICENSE
src/third_party/easyexif/exif.cpp
src/third_party/easyexif/exif.h

Add metadata in sfm_data.json
Propage visibility parameters

[WIP] Add metadata and visibility

---

src/software/RigCalibration/main_cameraCalibration.cpp

* it now directly generates the `.cal.txt`
* added param `-k2` to use only 2 distortion coefficients

calibration improvements

---

src/openMVG/dataio/AlembicExporter.cpp
src/openMVG/dataio/AlembicExporter.hpp
src/software/Localization/main_cctagLocalizer.cpp
src/software/Localization/main_voctreeLocalizer.cpp

Skip keyframe registration if camera is not localized

---

src/openMVG/matching_image_collection/Pair_Builder.hpp
src/openMVG/matching_image_collection/Pair_Builder_test.cpp

Connected to poparteu/openMVG#89

Fix contiguousWithOverlap in PairBuilder.hpp and add new test

---

src/openMVG/features/descriptor.hpp
src/openMVG/voctree/descriptor_loader.hpp
src/openMVG/voctree/descriptor_loader.tcc
src/openMVG/voctree/distance.hpp
src/openMVG/voctree/simple_kmeans.hpp
src/openMVG/voctree/tree_builder.hpp
src/software/Localization/createVoctree.cpp

Creation of a voctree using uchar descriptors.
connected  to poparteu/openMVG#104

Fix voctree

---

src/openMVG/dataio/AlembicExporter.cpp
src/openMVG/dataio/AlembicExporter.hpp
src/openMVG/dataio/AlembicImporter.cpp

connected to poparteu/openMVG#118

Add sensor height in ABC

---

src/openMVG/cameras/Camera_Common.hpp
src/openMVG/dataio/AlembicImporter.cpp
src/software/SfM/main_SfMInit_ImageListing.cpp

Connect to poparteu/openMVG#121

[imageListing] Use strings to set camera model from command line

---

src/openMVG/cameras/cameras.hpp
src/openMVG/features/descriptor.hpp
src/openMVG/voctree/CMakeLists.txt
src/openMVG/voctree/descriptor_loader.hpp
src/openMVG/voctree/kmeans_test.cpp
src/openMVG/voctree/voctreebuild_test.cpp

* Added voctree unit test (connected to poparteu/openMVG#44)
* Also fixes unhandled enumeration value `PINHOLE_CAMERA_FISHEYE` in switch for `createPinholeIntrinsic()`

Voctree unit tests

---

src/software/RigCalibration/main_cameraCalibration.cpp

Could also be done as a new command line option. Whatever you prefer.

Start calibration automatically with video file input.

---

src/openMVG/cameras/Camera_Intrinsics.hpp
src/software/SfM/main_SfMInit_ImageListing.cpp

Serial number = camera serial number + lens serial number
Closes #132

Add: serial number in camera intrinsics

---

src/openMVG/rig/Rig.cpp

Main and witness camera videos do not necessarily have the same number of frames.
Sequences are shortened to the shortest length sequence.

Rig calibration: allow different number of frames.

---

src/openMVG/robust_estimation/robust_estimator_ACRansac.hpp
src/openMVG/sfm/pipelines/sfm_matches_provider.hpp
src/software/RigCalibration/CMakeLists.txt
src/software/SfM/main_ComputeMatches.cpp
src/software/SfM/main_evalQuality.cpp

* misleading arg doc
* missing arg doc and printout
* improved code readability
* bugfix for acransac (see openMVG/openMVG#537)

fixes for ComputeMatches

---

src/openMVG/sfm/pipelines/sfm_engine.hpp
src/openMVG/sfm/sfm_data.cpp
src/openMVG/sfm/sfm_data.hpp
src/openMVG/sfm/sfm_landmark.hpp
src/software/SfM/main_ComputeSfM_DataColor.cpp
src/software/SfM/main_ConvertSfM_DataFormat.cpp
src/software/SfM/main_GlobalSfM.cpp
src/software/SfM/main_IncrementalSfM.cpp

connected to poparteu/openMVG#152
ComputeSfM_Data color can export to any supported format, not just `.ply`.

Computecolor

---

src/openMVG/sfm/sfm_landmark.hpp

connected to poparteu/openMVG#161

[sfm] changed order of declaration in Landmark

---

src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt

[sensor DB] added Sony Cyber-shot DSC-RX100 III

---

src/openMVG/robust_estimation/robust_estimator_LORansac.hpp

forgot to set it to false by default

loransac shut up

---

src/openMVG/localization/CCTagLocalizer.cpp
src/openMVG/localization/ILocalizer.hpp
src/openMVG/localization/VoctreeLocalizer.cpp
src/openMVG/localization/rigResection.cpp
src/openMVG/localization/rigResection.hpp
src/openMVG/localization/rigResection_test.cpp
src/openMVG/matching/regions_matcher.hpp
src/software/Localization/main_rigLocalizer.cpp
src/software/RigCalibration/main_rigCalibration.cpp
src/software/SfM/CMakeLists.txt

* some minor bugfixes
* exposed `_angularThreshold` for opengv rig localization

spur of the moment improvements

---

src/software/SfM/main_Align.cpp

Add an align vector to openmvg_main_Align. The ground plane and scale can be defined in meshroom. Written by @zvrba

Add align vector

---

src/openMVG/calibration/bestImages.cpp
src/openMVG/calibration/bestImages.hpp
src/openMVG/calibration/calibration.cpp
src/openMVG/calibration/calibration.hpp
src/openMVG/calibration/exportData.cpp
src/openMVG/calibration/exportData.hpp
src/openMVG/calibration/patternDetect.cpp
src/openMVG/calibration/patternDetect.hpp
src/openMVG/features/svgVisualization.cpp
src/openMVG/features/svgVisualization.hpp
src/software/Localization/main_cameraLocalizer.cpp
src/software/Localization/main_rigLocalizer.cpp
src/software/RigCalibration/main_cameraCalibration.cpp
src/software/RigCalibration/main_rigCalibration.cpp
src/software/SfM/main_ComputeFeatures.cpp

[calibration] add support for partially visible chessboards with CCTags

---

src/openMVG/localization/optimization.cpp
src/software/RigCalibration/CMakeLists.txt

* some formatting
* moved main_calibration inside a `if(OpenMVG_USE_OPENCV)`

[cmake] main_calibration must depend on OpenCV

---

src/software/Localization/main_rigLocalizer.cpp
src/software/Localization/pairListFromVoctree.cpp
src/software/Localization/voctreeQueryUtility.cpp
src/software/Localization/voctreeStatistics.cpp

connected to poparteu/openMVG#255

Fix bug create directories

---

src/openMVG/numeric/numeric.h
src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp

Fix stats on empty tracksLength vector

---

src/software/SfM/main_exportKeypoints.cpp

connected to alicevision/openMVG#271

export keypoints

---

src/openMVG/features/cctag/CCTAG_describer.cpp
src/openMVG/sfm/utils/sfm_data_UID_utils.cpp
src/software/Localization/voctreeStatistics.cpp
src/software/SfM/main_ComputeFeatures.cpp
src/software/SfM/main_ComputeMatches.cpp
src/software/SfM/main_FrustumFiltering.cpp

Some minor random fixes

---

src/openMVG/sfm/AlembicExporter.cpp
src/openMVG/sfm/AlembicExporter.hpp
src/openMVG/sfm/AlembicImporter.cpp
src/openMVG/sfm/AlembicImporter.hpp
src/openMVG/sfm/sfm_data_io.cpp
src/software/Localization/main_cameraLocalizer.cpp
src/software/Localization/main_rigLocalizer.cpp
src/software/RigCalibration/main_rigCalibration.cpp
src/software/SfM/main_ConvertAnimatedCamera.cpp

connected to alicevision/openMVG#253

fix wrong namespace for alembic {Ex,Im}porter

---

src/CMakeLists.txt
src/cmakeFindModules/cmake_uninstall.cmake.in

Added an uninstall rule to cmake in the popart_develop branch.

Cmake uninstall target

---

src/openMVG/dataio/FeedProvider.cpp
src/openMVG/dataio/FeedProvider.hpp
src/openMVG/dataio/VideoFeed.cpp
src/openMVG/dataio/VideoFeed.hpp
src/openMVG/localization/CCTagLocalizer.hpp
src/openMVG/localization/ILocalizer.hpp
src/openMVG/localization/VoctreeLocalizer.hpp
src/openMVG/localization/rigResection.cpp
src/openMVG/localization/rigResection.hpp
src/openMVG/sfm/AlembicExporter.cpp
src/openMVG/sfm/AlembicExporter.hpp
src/openMVG/sfm/AlembicImporter.cpp
src/openMVG/sfm/AlembicImporter.hpp
src/openMVG/sfm/sfm_data_io.cpp
src/software/Localization/main_cameraLocalizer.cpp
src/software/Localization/main_rigLocalizer.cpp
src/software/RigCalibration/main_rigCalibration.cpp
src/software/SfM/main_Align.cpp
src/software/SfM/main_ComputeSfM_DataColor.cpp
src/software/SfM/main_ConvertSfM_DataFormat.cpp
src/software/SfM/main_evalQuality.cpp

like eg a webcam. It uses the opencv interface. Useful if we need to do quick tests

[dataio] add support for live feed

---

src/openMVG/dataio/FeedProvider.cpp
src/openMVG/dataio/VideoFeed.cpp
src/openMVG/dataio/VideoFeed.hpp
src/openMVG/localization/CCTagLocalizer.hpp
src/openMVG/localization/ILocalizer.hpp
src/openMVG/localization/VoctreeLocalizer.hpp
src/openMVG/localization/rigResection.cpp
src/openMVG/localization/rigResection.hpp
src/openMVG/sfm/AlembicExporter.cpp
src/openMVG/sfm/AlembicExporter.hpp
src/openMVG/sfm/AlembicImporter.cpp
src/openMVG/sfm/AlembicImporter.hpp
src/openMVG/sfm/sfm_data_io.cpp
src/software/Localization/main_cameraLocalizer.cpp
src/software/Localization/main_rigLocalizer.cpp
src/software/RigCalibration/main_rigCalibration.cpp
src/software/SfM/main_Align.cpp
src/software/SfM/main_ComputeSfM_DataColor.cpp
src/software/SfM/main_ConvertSfM_DataFormat.cpp
src/software/SfM/main_evalQuality.cpp

* it replaces all the `#if HAVE_*` with `#ifdef HAVE_*`
* better use of comments for parameters

[all] use #ifdef instead of #if

---

src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp
src/openMVG/tracks/tracks.hpp
src/openMVG/tracks/tracks_test.cpp

just some stuff to make it safer

Bugfix common tracks in images 

---

src/software/SfM/main_openMVG2CMPMVS2.cpp

* export all views with a pose
* don't write any fixed resolution inside the generated .ini file

Remove single image resolution restriction in CMPMVS2 export

---

src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp

Ensure that images pairs with reasonable angle win but if there is no good angle in the whole dataset (like a LightField dataset), try all possible image pairs.

[sfm] incremental: initial image pair selection

---

src/aliceVision/sfm/AlembicExporter.cpp
src/software/pipeline/main_prepareDenseScene.cpp

Minor update in exporters

---

CONTRIBUTORS-libmv.md

Fix markdown formatting in CONTRIBUTORS file

---

INSTALL.md
src/software/pipeline/main_prepareDenseScene.cpp

Use UID for MVS

---

CMakeLists.txt
src/aliceVision/geometry/rigidTransformation3D.hpp
src/aliceVision/sensorDB/Datasheet.cpp
src/aliceVision/sfm/LocalBundleAdjustmentCeres.cpp
src/aliceVision/sfm/LocalBundleAdjustmentData.cpp
src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
src/aliceVision/system/Logger.cpp

Fix Windows build

---

src/aliceVision/fuseCut/DelaunayGraphCut.hpp

Improve performance during voting procedure by modifying `DelaunayGraphCut::mirrorFacet` method.
Use a `std::array` instead of a `std::set` in this method extensively used during the voting procedure.

FuseCut: performance improvement

---

src/aliceVision/mesh/MeshClean.cpp

Fix segfault during mesh post-processing in meshing step.
MeshClean: fix segfault in 'deployAll'

Fix segfault in Meshing step 

---

src/aliceVision/sfm/AlembicImporter.cpp

Add missing float => uchar color conversion.

AlembicImporter: fix landmarks color import

---

src/aliceVision/sensorDB/CMakeLists.txt
src/aliceVision/sensorDB/Datasheet.cpp
src/aliceVision/sensorDB/Datasheet.hpp
src/aliceVision/sensorDB/parseDatabase.cpp

Just minor c++11 stuff to make code simpler and more readable (hopefully)

[sensor DB] c++11ification

---

src/aliceVision/fuseCut/DelaunayGraphCut.cpp
src/aliceVision/fuseCut/ReconstructionPlan.cpp
src/aliceVision/mesh/Mesh.cpp
src/aliceVision/mesh/Mesh.hpp
src/aliceVision/mesh/MeshAnalyze.cpp
src/aliceVision/mesh/MeshClean.cpp
src/aliceVision/mesh/MeshClean.hpp
src/aliceVision/mesh/Texturing.cpp
src/aliceVision/mesh/UVAtlas.cpp
src/aliceVision/mesh/meshPostProcessing.cpp
src/aliceVision/mvsData/StaticVector.hpp
src/software/pipeline/main_meshFiltering.cpp

Minor refactoring on mesh clean

[mesh] minor refactoring

---

src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp

Fix performance issue of `remapLandmarkIdsToTrackIds`

---

src/aliceVision/mesh/Mesh.cpp
src/software/pipeline/main_meshDecimate.cpp
src/software/pipeline/main_meshDenoising.cpp

Fix mesh IO

---

CMakeLists.txt

[cmake] fix AV_BUILD_PNG=OFF

---

src/aliceVision/sensorDB/sensor_width_camera_database.txt
src/software/pipeline/main_cameraInit.cpp

Sensor database

---

INSTALL.md

[doc] INSTALL: precise the option to provide the path to cuda

---

appveyor.yml
cudaInstallAppveyor.cmd

This PR installs CUDA SDK and activates CUDA code compilation on AppVeyor.

[ci] AppVeyor: activate cuda build

---

src/aliceVision/camera/cameraCommon.hpp
src/aliceVision/sensorDB/Datasheet.cpp
src/aliceVision/sensorDB/Datasheet.hpp
src/aliceVision/sensorDB/parseDatabase.cpp
src/aliceVision/sensorDB/parseDatabase_test.cpp
src/aliceVision/sfm/View.hpp
src/aliceVision/sfm/viewIO.cpp
src/aliceVision/sfm/viewIO.hpp
src/software/pipeline/main_cameraInit.cpp

Improve software CameraInit

---

src/cmake/Helpers.cmake

`Helpers` use `RUNTIME DESTINATION` in `alicevision_add_sofware`

---

COPYING.md

Also sort dependencies by name.

[copying] add geogram, nanoflann and meshsdfilter

---

src/aliceVision/sensorDB/cameraSensors.db

Update cameraSensors.db with google pixel XL

---

src/aliceVision/sensorDB/cameraSensors.db

simple database add
changes nothing else

add Moto Z Play sensor

---

src/aliceVision/image/io.cpp

[imageIO] Remove intermediate useless image copy

---

src/aliceVision/feature/ImageDescriber.cpp
src/aliceVision/feature/akaze/AKAZE.cpp
src/aliceVision/feature/akaze/AKAZE.hpp
src/aliceVision/feature/akaze/ImageDescriber_AKAZE.cpp
src/aliceVision/feature/akaze/ImageDescriber_AKAZE.hpp
src/samples/featuresAKAZEDemo/main_computeAKAZE.cpp
src/samples/featuresRepeatability/main_repeatabilityDataset.cpp
src/samples/imageDescriberMatches/main_describeAndMatch.cpp
src/samples/robustHomographyGrowing/main_robustHomographyGrowing.cpp

AKAZE Grid filtering & formatting

---

src/aliceVision/depthMap/cuda/planeSweeping/plane_sweeping_cuda.cu

Minor depth map reformatting

---

INSTALL.md

Update documentation for building with CUDA 10 (which is fully compatible with Visual 2017) on Windows.

Update INSTALL.md for CUDA 10 on Windows

---

src/aliceVision/sensorDB/cameraSensors.db
src/aliceVision/sensorDB/parseDatabase.cpp
src/aliceVision/sensorDB/parseDatabase_test.cpp

---
Fix alicevision/meshroom#207
Fix alicevision/meshroom#226
Fix alicevision/meshroom#238
Fix alicevision/meshroom#287
Fix alicevision/meshroom#293
Fix alicevision/meshroom#295
Fix alicevision/meshroom#297
Fix #500 
Fix #515
Fix #519 
Fix #521 
Fix #533 
Fix #543

[sensorDB] Update sensor database & add information sources

---

src/aliceVision/depthMap/SemiGlobalMatchingParams.cpp
src/aliceVision/depthMap/SemiGlobalMatchingRc.cpp
src/aliceVision/mvsUtils/MultiViewParams.cpp
src/aliceVision/mvsUtils/MultiViewParams.hpp
src/aliceVision/mvsUtils/fileIO.cpp
src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.hpp
src/software/pipeline/main_depthMapFiltering.cpp
src/software/pipeline/main_incrementalSfM.cpp
src/software/pipeline/main_meshFiltering.cpp
src/software/pipeline/main_meshing.cpp
src/software/pipeline/main_prepareDenseScene.cpp

[software] Fix various options

---

src/software/pipeline/main_meshDenoising.cpp

Fixes https://github.com/alicevision/meshroom/issues/346
and https://github.com/alicevision/AliceVision/issues/564

Denoising outer iteration were ignored

---

src/aliceVision/localization/optimization.cpp
src/aliceVision/multiview/rotationAveraging/l2.cpp
src/aliceVision/multiview/translationAveraging/solverL1Soft.cpp
src/aliceVision/multiview/translationAveraging/solverL2Chordal.cpp
src/aliceVision/rig/Rig.cpp
src/aliceVision/sfm/BundleAdjustmentCeres.cpp

We have waited too much to merge #403 (for no good reason) and now too much things have changed in BA.
So it was easier to re-do the changes here.
Fix #403

Ceres 2 compatibility - again

---

src/aliceVision/fuseCut/DelaunayGraphCut.cpp
src/software/pipeline/CMakeLists.txt

- reduce log level for a warning that could appear on many vertices
- remove redondant cmake info

Minor things

---

src/aliceVision/sensorDB/cameraSensors.db

Listed as "Model alias" on devicespecifications.com:
https://www.devicespecifications.com/fr/model/8b1d43f8

[sensorDB] Add OnePlus5 "A5000" alias

---

src/software/pipeline/main_imageMatching.cpp

This PR fixes issues leading to an incorrect first line in the generated imageMatches.txt file.
Fix #534 
Prevent first line with no match caused by:
First image is now handled in the same loop as all others: first image ID in 'allMatches' map is the smallest one and will only have matches with larger IDs.

[sotfware] `ImageMatching` Fix `convertAllMatchesToPairList` function

---

CMakeLists.txt
Dockerfile

Update external libraries versions used in the all-in-one-build used in Docker for the linux release.

[cmake] Update external libraries versions

---

src/aliceVision/camera/CMakeLists.txt
src/aliceVision/camera/IntrinsicBase.hpp
src/aliceVision/camera/IntrinsicInitMode.hpp
src/aliceVision/sfmData/uid.cpp
src/aliceVision/sfmData/uid.hpp
src/aliceVision/sfmDataIO/AlembicExporter.cpp
src/aliceVision/sfmDataIO/AlembicImporter.cpp
src/aliceVision/sfmDataIO/alembicIO_test.cpp
src/aliceVision/sfmDataIO/jsonIO.cpp
src/aliceVision/sfmDataIO/sfmDataIO_test.cpp
src/aliceVision/sfmDataIO/viewIO.cpp
src/software/pipeline/main_cameraInit.cpp

Add an enum on intrinsics to describe if the intrinsics is calibrated, initialized or unknown to provide an explicit information about the initialization.

Camera intrinsics initialization

---

src/aliceVision/mesh/Mesh.cpp
src/aliceVision/mesh/Mesh.hpp
src/aliceVision/mesh/UVAtlas.cpp
src/aliceVision/mvsUtils/MultiViewParams.cpp

Improve "basic" unwrap mode by ensuring that we don't reduce the final resolution during the unwrap.

Improve unwrap quality

---

src/aliceVision/depthMap/DepthSimMap.cpp
src/aliceVision/fuseCut/Fuser.cpp

Add metadata to sim maps

---

src/aliceVision/sensorDB/cameraSensors.db

[SensorDB] ~100 models added

---

src/aliceVision/sensorDB/cameraSensors.db

LG Electronics;LG-H870DS;5.867

Added LG G6 Dual Sim

---

src/aliceVision/sensorDB/cameraSensors.db

Fix https://github.com/alicevision/meshroom/issues/495

[sensorDB] Update entry for Motorola G4 Plus

---

src/aliceVision/mesh/Texturing.cpp
src/aliceVision/mesh/Texturing.hpp

Some fixes (code cleaning, log update, default value for texture downscale parameter) for the release.

Fix texturing

---

src/aliceVision/sensorDB/cameraSensors.db

Added SONY ILCE 6300 to sensor database (is the internal name for the SONY A6300)

Updates cameraSensors.db

---

src/CMakeLists.txt

[cmake] fix opencv version requirement

---

src/CMakeLists.txt
src/aliceVision/hdr/DebevecCalibrate.cpp
src/aliceVision/hdr/GrossbergCalibrate.cpp
src/aliceVision/hdr/RobertsonCalibrate.cpp
src/aliceVision/hdr/hdrMerge.cpp
src/software/convert/main_convertLDRToHDR.cpp

[software] LDR2HDR : add automatic generated name for output

---

src/aliceVision/sensorDB/cameraSensors.db

Added huawei P20 to sensor database

Added Huawei P20 to sensors

---

src/aliceVision/sensorDB/cameraSensors.db

Fixed Xiaomi A1 entry
Added Google Pixel 3a to ```cameraSensors.db```  
Fixed Xiaomi A1 entry

Added Google Pixel 3a to database

---

src/software/pipeline/main_depthMapEstimation.cpp

Fix a typo

---

src/aliceVision/sensorDB/cameraSensors.db

from https://github.com/alicevision/meshroom/issues/699

Add new camera models

---

src/aliceVision/sensorDB/cameraSensors.db

Add 100+ models to sensordb

---

src/aliceVision/system/CMakeLists.txt
src/aliceVision/system/Logger.cpp
src/aliceVision/system/Logger.hpp
src/aliceVision/system/Logger_test.cpp

* fixed a bug for which the logger levels were not case insensitive
* move code to cpp
* added unit test for logger

[system] Logger levels were not case insensitive

---

src/software/pipeline/main_featureMatching.cpp
src/software/pipeline/main_imageMatching.cpp

image matching: fix min nb images

---

src/software/pipeline/main_meshDenoising.cpp

Fix typo and add publication title in comments for reference
Wang et al. 2015 https://dl.acm.org/citation.cfm?id=2818068

fixed citation

---

src/aliceVision/sensorDB/cameraSensors.db

Added Sony Xperia XZ2 to sensor database (H8266)

Update camerasensors.db with Sony Xperia XZ2

---

src/aliceVision/sensorDB/cameraSensors.db

https://github.com/alicevision/meshroom/issues/792

Add OnePlus 7T PRO

---

src/aliceVision/sensorDB/cameraSensors.db

Added Xiaomi Redmi 5A sensorwidth to the database
I have added Xiaomi Redmi 5A's sensor info to the database

Added a camera

---

src/aliceVision/sensorDB/cameraSensors.db

Found on https://www.deviceranks.com/en/camera-sensor/42/sony-imx363-exmor-rs

camera sensors: add pocophone F1

---

src/software/utils/main_imageProcessing.cpp

[software] imageProcessing: remove trailing includes

---

COPYING.md
src/CMakeLists.txt

SIFT is now free: opencv/opencv_contrib#2449

[build] sift_ocv option

---

src/aliceVision/prettyprint.hpp

[build] fix prettyprint MSVC compatibility

---

src/aliceVision/sensorDB/cameraSensors.db

Sony;Sony HDR-HC7e;4.98;usercontribution

Added: Sony;Sony HDR-HC7e;4.98;usercontribution

---

src/aliceVision/voctree/Database.cpp
src/aliceVision/voctree/Database.hpp
src/software/pipeline/main_imageMatching.cpp

Image Matching fixes

---

src/aliceVision/sfmData/View.hpp

Add some aliases for some image metadatas (As set by nuke exr exporter)

Add aliases for nuke metadata

---

src/software/pipeline/CMakeLists.txt
src/software/pipeline/main_panoramaCompositing.cpp

Graph cut seam selection for panorama compositing
Graph cut based seam selection

Panorama: Add Graphcut in compositing

---

src/aliceVision/sfm/BundleAdjustmentPanoramaCeres.cpp
src/aliceVision/sfm/BundleAdjustmentPanoramaCeres.hpp
src/aliceVision/sfm/pipeline/panorama/ReconstructionEngine_panorama.cpp

Just removed some variables which were unused or useless.

[sfm] Remove useless ordering for panorama

---

src/software/pipeline/main_panoramaWarping.cpp

Select the ratio of pixels which will be upscaled in the panorama

[software] PanoramaCompositing: option to select the percentage of upscaled pixels

---

CONTRIBUTORS.md

Add @Julien-Haudegond and @dsmtE to the list of contributors.

Add Julien Haudegond and Enguerrand De Smet

---

src/software/pipeline/main_panoramaCompositing.cpp

[software] PanoramaCompositing: add graphcut border check

---

src/software/pipeline/main_panoramaInit.cpp

Add some new restriction to circle detection

[software] PanoramaInit: Add new restriction to circle detection

---

src/aliceVision/sensorDB/cameraSensors.db

Added Nikon D780 to cameraSensors.db

Added Nikon D780

---

src/aliceVision/sfmData/View.hpp
src/aliceVision/sfmData/uid.cpp
src/software/export/main_exportAnimatedCamera.cpp
src/software/pipeline/main_panoramaEstimation.cpp

Add timestamp reading to View.
Allow ordering of inputs by time (for center of panorama selection)

[software] PanoramaEstimation: sort input images by shooting time to select the center camera

---

src/aliceVision/hdr/hdrMerge.cpp
src/aliceVision/sfmData/View.hpp

Small update to avoid infinite values in HDR 16 bits EXR

[sfmData] change reference f-number

---

src/software/utils/main_sfmTransfer.cpp

Enable Copy of intrinsics between two similar sfmdata

[software] SfMTransfer: New option to copy intrinsics from one sfmdata to another

---

src/software/pipeline/main_panoramaWarping.cpp

Using same rounding for manual and automatic mode

[Panorama] Using a common power of two rounding for manual and automatic sizes

---

src/software/pipeline/main_LdrToHdrCalibration.cpp
src/software/pipeline/main_LdrToHdrMerge.cpp
src/software/pipeline/main_panoramaWarping.cpp

ldr2hdr: fix bypass option

---

INSTALL.md

[doc] Install: update minimal version of dependencies

---

src/aliceVision/sfm/pipeline/panorama/ReconstructionEngine_panorama.cpp
src/aliceVision/sfmDataIO/viewIO.cpp
src/software/pipeline/main_cameraInit.cpp

Based on basic file naming convention.
Could be used for multi-bracketing images and/or acquisition with different lightings.

[software] CameraInit: allow to assign the same pose to multiple images

---

src/aliceVision/multiview/rotationAveraging/rotationAveraging_test.cpp
src/aliceVision/sfm/pipeline/panorama/ReconstructionEngine_panorama.cpp
src/aliceVision/sfm/pipeline/panorama/ReconstructionEngine_panorama.hpp
src/aliceVision/sfm/pipeline/regionsIO.cpp
src/aliceVision/sfmData/SfMData.cpp
src/aliceVision/sfmDataIO/AlembicExporter.cpp
src/aliceVision/sfmDataIO/AlembicExporter.hpp
src/aliceVision/sfmDataIO/AlembicImporter.cpp
src/aliceVision/sfmDataIO/sfmDataIO.cpp
src/software/convert/main_convertSfMFormat.cpp
src/software/pipeline/main_panoramaEstimation.cpp
src/software/pipeline/main_panoramaInit.cpp

Panorama: new options to init with known poses

---

src/aliceVision/sensorDB/cameraSensors.db

Sony a7R IV added
https://github.com/alicevision/AliceVision/issues/943

more cameras

---

src/aliceVision/fuseCut/DelaunayGraphCut.cpp
src/aliceVision/fuseCut/DelaunayGraphCut.hpp
src/aliceVision/fuseCut/DelaunayGraphCut_test.cpp
src/aliceVision/fuseCut/delaunayGraphCutTypes.hpp
src/aliceVision/mvsData/Point3d.hpp
src/software/pipeline/main_meshing.cpp

Reduce noise in the results with a post-processing of the graph-cut results.

[fuseCut] new cells status filtering by solid angle ratio

---

src/aliceVision/sensorDB/cameraSensors.db

Add motorola moto g7 sensor width

---

src/aliceVision/fuseCut/DelaunayGraphCut.cpp
src/aliceVision/fuseCut/DelaunayGraphCut.hpp
src/aliceVision/fuseCut/DelaunayGraphCut_test.cpp
src/aliceVision/mvsData/Point3d.hpp
src/software/pipeline/main_meshing.cpp

More control on graph cut post processing

---

src/aliceVision/sfm/ResidualErrorFunctor.hpp

Remove in place rotation of a point in ceres cost function

[sfm] in place rotation of point is not allowed in ceres

---

src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.hpp
src/software/pipeline/main_incrementalSfM.cpp

[sfm] make sure everything is deterministic again

---

src/software/utils/CMakeLists.txt
src/software/utils/main_split360Images.cpp

- add fov param
- set focal in mm (and not in pixels)
- fix behavior regarding resolution/fov params
- add nbThreads param

[software] split360: some fixes

---

src/aliceVision/sensorDB/cameraSensors.db

Added the necessary information to the camera DB for the DJI Mavic Air 2
Cheers :)

[sensordb] DJI Mavic Air 2

---

src/aliceVision/sensorDB/cameraSensors.db

Updated database with sensors Pixel 4a 5G and Pixel 5 (which have the same sensor).

Updated database with sensors Pixel 4a 5G and Pixel5

---

src/aliceVision/sensorDB/cameraSensors.db

https://www.blackmagicdesign.com/products/blackmagicpocketcinemacamera/techspecs/W-CIN-12

[sensorDB] Add Blackmagic Pocket Cinema Camera 4K

---

src/aliceVision/sensorDB/cameraSensors.db

The model to need to read is Xiaomi M2007J20CG. The Physical sensor size is 7.4×5.6 mm I found this site: https://www.camerafv5.com/devices/manufacturers/xiaomi/m2007j20cg_surya_0/

I have add for Xiaomi POCO X3

---

INSTALL.md

- [doc] install: avoid dependency to qt

[doc] install update for windows

---

src/aliceVision/camera/Equidistant.hpp
src/aliceVision/camera/IntrinsicBase.hpp
src/aliceVision/camera/Pinhole.hpp
src/aliceVision/camera/equidistant_test.cpp
src/aliceVision/camera/pinhole3DE_test.cpp
src/aliceVision/camera/pinholeBrown_test.cpp
src/aliceVision/camera/pinholeFisheye1_test.cpp
src/aliceVision/camera/pinholeFisheye_test.cpp
src/aliceVision/camera/pinholeRadial_test.cpp
src/aliceVision/geometry/Pose3.hpp
src/aliceVision/image/image_test.cpp
src/aliceVision/localization/rigResection_test.cpp
src/aliceVision/panorama/coordinatesMap.cpp
src/aliceVision/panorama/remapBbox.cpp
src/aliceVision/rig/Rig.cpp
src/aliceVision/sfm/BundleAdjustmentPanoramaCeres.cpp
src/aliceVision/sfm/BundleAdjustmentSymbolicCeres.cpp
src/aliceVision/sfm/BundleAdjustmentSymbolicCeres.hpp
src/aliceVision/sfm/bundleAdjustment_test.cpp
src/aliceVision/sfm/generateReport.cpp
src/aliceVision/sfm/pipeline/RigSequence.cpp
src/aliceVision/sfm/pipeline/panorama/panoramaSfM_test.cpp
src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
src/aliceVision/sfm/sfmFilters.cpp
src/aliceVision/sfm/sfmStatistics.cpp
src/aliceVision/sfm/sfmTriangulation.cpp
src/aliceVision/sfm/utils/statistics.cpp
src/samples/robustEssential/main_robustEssential.cpp
src/software/pipeline/main_meshing.cpp

Update the symbolic bundle adjustment to be on par with updates of the classical bundle adjustment options.

Update symbolic Bundle Adjustment

---

README.md

The link to the paper will be updated when it becomes public.

[doc] readme: update citation

---

src/aliceVision/mesh/Mesh.cpp
src/aliceVision/mesh/Mesh.hpp
src/software/convert/main_convertMesh.cpp
src/software/pipeline/main_meshFiltering.cpp
src/software/pipeline/main_meshMasking.cpp
src/software/pipeline/main_meshing.cpp

Some minor cleanup of https://github.com/alicevision/AliceVision/pull/1092.

[mesh] use file extension to choose the file format

---

README.md

[doc] fix bibtex

---

CMakeLists.txt
src/aliceVision/sensorDB/cameraSensors.db

- Update libraw
- Add to sensordb

Add support for Canon R5

---

src/aliceVision/sensorDB/cameraSensors.db

https://www.kimovil.com/en/where-to-buy-huawei-honor-view-20#sec-camera
https://www.deviceranks.com/en/camera-sensor/666/sony-imx586-exmor-rs

[sensorDB] add Huawei Honor 20 View

---

src/aliceVision/sensorDB/cameraSensors.db

~30 pro cams added

---

src/aliceVision/sensorDB/cameraSensors.db

Add new entry for cameraSensors.db

---

src/software/pipeline/main_distortionCalibration.cpp

Stmap debug output was badly normalized (wrt output instead of input)

bad computation for stmap output

---

src/aliceVision/sensorDB/cameraSensors.db

Add Google Pixel 6 and 6 Pro to the sensors database (same sensor)

Add Pixel 6 and 6 Pro

---

src/aliceVision/sensorDB/cameraSensors.db

I added a sensor model of my smartphone

update sensordb samsung sm g785g

---

INSTALL.md

[INSTALL] Update Vcpkg link to AliceVision Vcpkg fork (last tested commit).

[doc] INSTALL: Update Vcpkg link

---

CMakeLists.txt

Update zlib to latest release, as 1.2.11 no longer served by zlib.net

update zlib dependency

---

.github/workflows/stale.yml

Fixes #1139 by updating actions/stale.

Update actions/stale to latest version v5

---

.github/workflows/continuous-integration.yml
INSTALL.md

Use a custom version of vcpkg with a fix to avoid imath/openexr-2 incompatibility.

[ci] upgrade vcpkg version

---

src/aliceVision/sensorDB/cameraSensors.db

https://www.dji.com/fr/mavic-3/specs
CMOS 4/3 (17.3x13 mm)

[sensorDB] Add DJI Mavic3

---

src/aliceVision/fuseCut/DelaunayGraphCut.cpp

Add missing std namespace needed for recent g++ compiler.

[build] fixes for recent g++ compiler

---

INSTALL.md

https://github.com/alicevision/AliceVision/pull/1055

[doc] Install: update minimal version of mosek

---

src/aliceVision/sensorDB/cameraSensors.db

added DJI MAVIC2-ENTERPRISE-ADVANCED

[sensorDB] Add DJI MAVIC2-ENTERPRISE-ADVANCED

---

src/aliceVision/sensorDB/cameraSensors.db

Adding Canon PowerShot G5 X Mark II to cameraSensors.db

[sensorDB] Adding Canon PowerShot G5 X Mark II

---

src/aliceVision/sensorDB/cameraSensors.db

i added the phone huawei p30 pro

[sensorDB] Added the phone Huawei p30 pro

---

src/aliceVision/sensorDB/cameraSensors.db

added Xiaomi Poco X3 Pro sensor (IMX582)

[sensorDB] Add Xiaomi Poco X3 Pro (IMX582)

---

src/aliceVision/imageMatching/ImageMatching.cpp
src/aliceVision/imageMatching/ImageMatching.hpp

Fix change in file format introduced in https://github.com/alicevision/AliceVision/pull/1270.
ImageMatching is not yet included in the functional tests, we should add it.
Fix https://github.com/alicevision/AliceVision/issues/1279

[imageMatching] bug fix: file format exporter

---

src/software/pipeline/CMakeLists.txt
src/software/pipeline/main_sfmTriangulation.cpp
src/software/pipeline/main_triangulate.cpp

Adds a main that is essentially the triangulation step from the sequential SfM.
Meshroom pr : https://github.com/alicevision/Meshroom/pull/1842
This allows to run the triangulation without going into the sfm step.
Duplicated the code, might not be optimal.

[software] New triangulation tool

---

src/aliceVision/image/cache.hpp

Add missing ```#include <list>``` previously include by Boost before its 1.81.0 release.
Fixes #1332

[image] Fix build failure with Boost 1.81.0

---

src/software/pipeline/main_panoramaCompositing.cpp

Each input image composing the panoramas contains metadata.
This PR takes the metadata FROM one input image and write  it ONTO the output composited images.
The Panorama merging node is already passing the metadata correctly so nothing had to be done.

[panorama] Propagate metadatas

---

src/aliceVision/mesh/Texturing.cpp
src/aliceVision/mesh/Texturing.hpp
src/software/pipeline/main_texturing.cpp

Rename 'processColorspaceName' option in 'workingColorSpace' and add 'outputColorSpace' option.

Texturing Color Space

---

INSTALL.md

Update the INSTALL.md moving coin libs in the required dependencies
fix #1396

[doc] coin libs are required

---

src/software/pipeline/main_LdrToHdrMerge.cpp

For the HDR image filenames, allow to keep filenames of the input images selected as central ones in hdr merging.

HDR filenames

---

src/aliceVision/sfm/utils/alignment.cpp

computeNewCoordinateSystemFromSingleCamera function algorithm was invalid.
I did not understand the previous choice and replaced the code to fit the real geometric problem.

computeNewCoordinateSystemFromSingleCamera was not correct

---

.gitignore

Ignore Visual Studio and Visual Studio Code project folders

[gitignore] Update .gitignore

---

CHANGES.md
CMakeLists.txt
CONTRIBUTORS.md
INSTALL.md
src/aliceVision/version.hpp

Release 3.1
